### ISSUE TITLE
Problema no susy

### ISSUE THREAD

**Issue by Hunterms** [iagoac/mc202#10]
Boa noite, fui submeter o lab e o susy retornou a tela em anexo qnd cliquei em "Turmas registradas"

![image](https://user-images.githubusercontent.com/32364098/79283872-7e250580-7e8f-11ea-9705-f8263a5f24ac.png)

**Comment by iagoac** [comment]
Olá @Hunterms,

a página correta é https://susy.ic.unicamp.br:9999/mc202defg
Eu acabei de fazer o upload da tarefa e verificar tudo. Parece que está OK
