### ISSUE TITLE
Entrega do lab 5 e uso do Mergesort

### ISSUE THREAD

**Issue by Alandroid** [iagoac/mc202#102]
Olá professor. 

Gostaria de saber se a data correta de entrega do lab 05 é dia 03, como no Susy, ou amanhã, como no enunciado da atividade.

Também gostaria se saber se há problemas em usarmos a implementação da Mergesort que já existe nos slides da disciplina, apenas fazendo as adaptações para contabilizar o número de inversões na fila.

Obrigado

**Comment by Antonio-Silvestre** [comment]
Estou com a mesma dúvida.

**Comment by marinabmorais** [comment]
vou aproveitar pra perguntar se o lab7 é pro dia 03/06 também, pq no readme ta escrito que é pro  08/06

**Comment by iagoac** [comment]
Parece que eu me confundi um pouco com as datas :(  
Bem, pra não prejudicar ninguém, vou deixar o maior prazo entre todos os que foram anunciados em algum local.

Desta forma, a data do lab 05 é para 03/06 e a do lab 07 é para 08/06.

Vou atualizar as datas no Susy.

**Comment by iagoac** [comment]
> Também gostaria se saber se há problemas em usarmos a implementação da Mergesort que já existe nos slides da disciplina, apenas fazendo as adaptações para contabilizar o número de inversões na fila.

Desde que vocês realmente entendam o que está acontecendo, não vejo muitos problemas nisso.  
Entretanto, eu vou rodar um detector de plágio no trabalho de todo mundo. Se todos copiarem o mesmo código dos slides, acredito que vai dar problema
