### ISSUE TITLE
(código 139) Lab5

### ISSUE THREAD

**Issue by JonasRoberto** [iagoac/mc202#103]
No Lab5 eu fiz o codigo e ele funciona normalmente mas quando submeto no Susy ele fala isso: 
"Erro de processamento
tamanho máximo da pilha ou da memória dinâmica excedido, 
ou talvez apontador inválido (código 139)".
Tentei mudar muitas coisas mas não entendo se passei o O(nlogn) ou o codigo tenta acessar valores alem do vetor ou algo assim. Alguma ideia do que possa ser esse problema?

**Comment by iagoac** [comment]
@JonasRoberto a questão do O(n log n) é simplesmente sobre a complexidade máxima do algoritmo.  
Um Quick Sort ou Merge Sort tem uma função de complexidade, no pior caso, n log n.  
Diferentemente destes, um Bubble Sort ou Insertion Sort tem uma função de complexidade, no pior caso, de n².

Já sobre o erro 139, você pode encontrar outras discussões [aqui](https://github.com/iagoac/mc202/issues/65). Diversos outros alunos já tiveram este erro em labs passados.  
O seu código funciona normalmente em seu computador pois os exemplos que você utiiza são menos complexos que os casos de teste do Susy.

**Comment by JonasRoberto** [comment]
eu tive a ajuda de um PED para usar as entradas e ele falou que usou as entradas do Susy e funcionou, mas quando eu submeto no Susy da esse erro.

**Comment by enoque** [comment]
Provavelmente você está usando muita memória de pilha e a "pilha" do susy é menor que a do seu computador. A memória de pilha é basicamente o quanto seu computador consegue criar variáveis locais, e essa memória costuma ser bem menor que a memória de heap. 

Pra ajudar você entender melhor, segue o artigo [aqui](https://blog.pantuza.com/artigos/heap-vs-stack). Existem formas de aumentar essa pilha e tentar ver se dá certo, mas recomendo você procurar onde você está excedendo no uso de memória.

**Comment by tr0fin0** [comment]
@JonasRoberto, em meu laboratório 04 passei por esse problema. Recomendo que você reveja as atribuições de variáveis para certificar que todas estão declaradas adequadamente, sem receber lixo nem acessando posições de memórias inválidas, e avalie o funcionamento de seu código.

No meu caso uma das funções demandava demasiado espaço da memória sem necessidade, gerando o problema no Susy.

**Comment by JonasRoberto** [comment]
Apontava algum problema na fase de compilação?
Aqui não aponta nenhum só da esse erro na fase de execução.

**Comment by tr0fin0** [comment]
Não aponta problema de compilação, este problema só ocorre durante o funcionamento do código. A compilação avalia se o código está "ok", a execução acusa problemas do funcionamento.

**Comment by iagoac** [comment]
Normal não apontar erro em fase de compilação.  

A sintaxe do código, em si, está correta.  
Entretanto, o compilador não tem como prever um acesso errado a memória ou estouro de tamanho de pilha, dentre outras coisas, pois isto depende da entrada.  
Deste modo, o erro acontece em tempo de execução.

**Comment by JonasRoberto** [comment]
Consegui, com a ajuda do PAD e de um aluno, o problema era que todas minhas entradas estavam em int e depois eu coloquei todas em long long int. Para deixar correto eu tive que mesclar, uma eram int e outras long long int.
Obrigado a todos que comentaram tambem, ajudou bastante.
