### ISSUE TITLE
Dúvida Lab 07

### ISSUE THREAD

**Issue by pedro-ferraz** [iagoac/mc202#104]
Qual o critério de escolha do k-ésimo menor número para um caso em que haja menores números repetidos?
Por exemplo, no terceiro exemplo de saída, se k fosse 2, que saída eu deveria esperar? O segundo menor 2, ou o 3 (desprezando-se repetições)?

![Sem título](https://user-images.githubusercontent.com/63692033/83453505-fc823a80-a430-11ea-801c-46e2ab6528a5.png)

Dessa forma, em uma entrada do tipo: N = 5, k = 2 e números = 1 1 1 1 1, eu retorno uma mensagem de erro ou retorno "1"?

**Comment by Tomikins** [comment]
Retorna 1 mesmo (:


Tomais Gonçalves Peluso
Estudante de Ciência da Computação - Unicamp


Em seg., 1 de jun. de 2020 às 17:59, pedro-ferraz <notifications@github.com>
escreveu:
