### ISSUE TITLE
lab5, mudança de long long int para int

### ISSUE THREAD

**Issue by JonasRoberto** [iagoac/mc202#105]
eu tinha escrito esta duvida https://github.com/iagoac/mc202/issues/103 e consertei trocando long long int com int em alguma variaveis, mas antes o codigo dava todas as saidas corretamente, mas não funcionava no Susy, agora ele funciona no Susy e não da as saidas corretamente, eu não entendi o porque disso, eu só troquei long long int para int, não mudei uma linha a mais. alguem tem alguma ideia do que fazer?
OBS: os valores estão saindo errado em uma diferença exata de 100mil para o valor correto, mas não são todas saidas que estão com esse erro, algumas ainda estão certas.

**Comment by iagoac** [comment]
@JonasRoberto você está inicializando as variáveis corretamente?  
Se todos os resultados estão com uma diferença exata de 100 mil do resultado correto, acredito que seja algum erro de inicialização ou alguma atribuição que você faz em algum momento de seu código.

Dê uma conferida que provavelmente você vai encontrar algo do tipo.

**Comment by JonasRoberto** [comment]
estou inicializando as variaveis corretamente e não são todos os valores que possuem essa diferença de valor, alguns acertam na saida. Minha duvida é porque deu essa diferença se eu só mudei o long long int para int, quando era tudo long long int todos os valores estavam certos.

**Comment by iagoac** [comment]
Bem, mas qual foi o motivo de você mudar de `long long int` para `int`?  
Diversos colegas da sua turma estão tomando a direção contrária, pois um simples `int` não é capaz de contar todas as inversões.

Já tivemos algumas discussões anteriores sobre este assunto [aqui](https://github.com/iagoac/mc202/issues/100)

**Comment by JonasRoberto** [comment]
eu mandei o link onde eu conto o motivo de ter mudado, é que eu coloquei long long int em tudo e o Sussy não aceitou, ai eu ponderei e deixei apenas minha variavel contadora com long long int ai o Susy aceitou e rodou meu codigo, mas agora ele da valores diferentes de antes quando era tudo long long int. Isso que eu não entendi, eu só mudei o formato de long long int para int e o codigo esta dando outros valores.

**Comment by iagoac** [comment]
Você está fazendo esta contagem dentro de alguma função?  
Caso seja este o caso, a função também deverá retornar um `long long int` e contar utilizando um `long long int`. Todas as outras variáveis podem ser `int` normalmente.

**Comment by JonasRoberto** [comment]
eu fiz isso, posso mandar o codigo por e-mail se quiser, eu apenas mudei as outras variaveis, minha contadora continua em todas as funções como long long int

**Comment by iagoac** [comment]
@JonasRoberto você solucionou seu problema?

**Comment by JonasRoberto** [comment]
O PED me ajudou, deu certo sim.
