### ISSUE TITLE
duvida lab7 (e lab5)

### ISSUE THREAD

**Issue by marinabmorais** [iagoac/mc202#106]
Oi! No enunciado dos dois ultimos labs está escrito nas restrições que "você deverá implementar qualquer estrutura de dados que utilizar". Queria saber se podemos usar vetores estáticos mesmo? Fiz meu lab5 usando vetor, mas agora to em dúvida se tem problema...

**Comment by iagoac** [comment]
@m-abi discutimos este assunto previamente [aqui](https://github.com/iagoac/mc202/issues/97).  
Ainda mantenho a minha posição

**Comment by marinabmorais** [comment]
não tenho certeza se entendi sua resposta no outro issue :/
no lab5 eu apenas usei vetor da forma que estamos acostumados, isso esta inadequado? não entendi oq seria _implementar_ um vetor...

**Comment by iagoac** [comment]
Você deve implementar caso você utilize alguma estrutura especial.  
Caso você não utilize nada, não tem sentido implementar 😄 

Caso você tenha implementado este laboratório utilizando somente vetores, não tem problema algum.

**Comment by marinabmorais** [comment]
ahh, então ta certo! hahah
obrigada professor :)
