### ISSUE TITLE
Submissão fora do prazo LAB05

### ISSUE THREAD

**Issue by igorloss500** [iagoac/mc202#108]
Boa tarde professor, 
Vi que você disponibilizou no susy a opção de submeter labs em atraso, no entanto, quando fui submeter o lab05, deu um erro dizendo:

"Submissão antes do inicio ou fora do prazo".

Seria possível liberar a submissão fora de prazo desse lab também?

Atenciosamente,
Igor

**Comment by laryssalgr** [comment]
Eu tive o mesmo problema com a submissão do lab02.

**Comment by iagoac** [comment]
Eu reabri somente os labs 01 a 04 para submissão atrasada, por hora.  
Vou reabrir o 05 hoje a tarde.

@laryssalgr o lab02 não está aberto novamente? Quando você testou isso?

**Comment by igorloss500** [comment]
> Eu reabri somente os labs 01 a 04 para submissão atrasada, por hora.
> Vou reabrir o 05 hoje a tarde.
> 
> @laryssalgr o lab02 não está aberto novamente? Quando você testou isso?

**Comment by igorloss500** [comment]
Obrigado professor. Poderia por favor avisar quando a submissão para o lab 05 estiver disponível?

Att,
Igor

**Comment by laryssalgr** [comment]
Olá professor,
Eu testei novamente hoje, e conferi que realmente os labs 1, 3 e 4 tiveram
seus prazos de entrega alterados, porém o 2 não.
Segue em anexo a minha tentativa de submissão com a data de hoje.
[image: image.png]

Em seg., 8 de jun. de 2020 às 11:00, Iago Augusto de Carvalho <
notifications@github.com> escreveu:

**Comment by iagoac** [comment]
@igorloss500 @laryssalgr alterei novamente agora.  
Também reabri o laboratório 05 para entregas atrasadas.

**Comment by igorloss500** [comment]
Obrigado, professor. Deu tudo certo.
