### ISSUE TITLE
Dúvida Sobre o print dos resultados do lab9

### ISSUE THREAD

**Issue by RPanosso** [iagoac/mc202#110]
Acredito que os erros sejam com espaçamentos, eu coloquei apenas um espaço entre os dois números e não deu, tentei também um espaço antes pois parecia ter um espaço antes dos resultado, mas mesmo assim não vai

printf(" %d %d", altura1, altura2);
printf("%d %d", altura1, altura2);

Tentei desses dois jeitos

![Screenshot_201](https://user-images.githubusercontent.com/62064785/84792945-e21c9500-afca-11ea-9861-69f778dbcb25.png)

**Comment by Tomikins** [comment]
Faltou a quebra de linha depois dos resultados (:
