### ISSUE TITLE
Notas turma E

### ISSUE THREAD

**Issue by sentineladonorte** [iagoac/mc202#111]
Professor, tem um erro na planilha de notas da turma E, a notas não estão correspondendo a respectiva linha em q se encontram

**Comment by sentineladonorte** [comment]
vi agora também que na formula não esta sendo considerada os dois últimos labs

**Comment by igorloss500** [comment]
As notas dos labs entregues em atraso, no meu caso o lab 5, também não foram computadas.

**Comment by iagoac** [comment]
@RafaelAllves vou arrumar a fórmula.
@igorloss500 os labs entregues em atraso só serão computados no dia 10 de julho.
