### ISSUE TITLE
Entrega atrasada lab 09

### ISSUE THREAD

**Issue by igorloss500** [iagoac/mc202#112]
Bom dia professor,

Tive complicações com os testes do lab09 no susy, com a seguinte mensagem:

"erro de processamento tamanho máximo da pilha ou da memória dinâmica excedido,
ou talvez apontador inválido (código 139)".

E não consegui entregar no prazo, gostaria de saber se é possível enviá-lo valendo menos.
Desde já, muito obrigado.

Atenciosamente,
Igor

**Comment by iagoac** [comment]
@igorloss500 pode sim.  
Vou abrir o lab para entregas atrasadas, da mesma forma como todos os outros.

**Comment by igorloss500** [comment]
Poderia, por favor, avisar quando abrir?
Att,
Igor

**Comment by iagoac** [comment]
@igorloss500 ta aberto!

**Comment by igorloss500** [comment]
Muito obrigado professor!

Outra coisa, te mandei um email solicitando ajuda, pois não consegui identificar o erro. 
Você está atendendo solicitações via email ou só por aqui mesmo?

**Comment by igorloss500** [comment]
Professor,

Fui submeter no susy e aparece a mensagem de que o limite de submissões foi excedido... Poderia, por favor liberar para que eu consiga realizar a submissão novamente? Consegui arrumar o problema com meu lab.

Desde já, agradeço.
Igor

**Comment by igorloss500** [comment]
Só pra esclarecer, enquanto estava no prazo, eu submeti 19 vezes pois no meu PC o código estava funcionando normalmente e passando no testes, mas estava com problemas no susy.

**Comment by iagoac** [comment]
@igorloss500 vou olhar seu código hoje.  
Além disso, vou aumentar o número de submissões para 40

**Comment by igorloss500** [comment]
Obrigado professor, acho que consegui solucionar o problema do lab. Submeti no susy com sucesso.

Att,
Igor
