### ISSUE TITLE
LAB10 - Como criar ponteiro para NULL?

### ISSUE THREAD

**Issue by victorpmacc** [iagoac/mc202#113]
Boa noite!
Estou com uma dúvida matadora para realização do LAB10: como eu consigo fazer um ponteiro já existente, apontar para NULL? 
Tenho uma tabela hash estruturada na forma ponteiro para ponteiros: ` tabela[i]` guarda o endereço de um valor `*tabela[ i ]`. Consigo fazer qualquer alteração no valor guardado ou no endereço de tal valor, mas como é possível fazer com que `tabela[i]`, que é ponteiro para inteiro, aponte para NULL?

**Comment by iagoac** [comment]
@victorpmacc até onde eu sei, é simples vc ter uma variável do tipo ```int *ponteiro = NULL```.   

Por favor, você pode postar aqui a declaração da sua tabela e a forma como você aloca a memória?

**Comment by victorpmacc** [comment]
Olá Iago! Acabei conseguindo solucionar o problema.
Segue a declaração de tabela que eu usei:
```
int** tabela;
tabela = malloc(N * sizeof(int *));
// Inicializar tabela
for(int i= 0; i < N; i++){
  tabela[i] = malloc(sizeof(int));
  tabela[i] = NULL;
}
```
Eu estava tendo erros pois, em primeiro momento, estava atribuindo NULL ao valor int, na última linha: `*tabela[i] = NULL`, o que está errado e me gerava warnings.
Em segundo momento, na atribuição de valores para os slots da tabela, eu estava jogando os valores int entrados diretamente em `*tabela[i]`, que estavam apontando para NULL na inicialização, o que me gerava um segmentation fault, daí que surgiu a dúvida deste post - mas acontece que o problema não estava na atribuição do NULL, mas na passagem dos valores. Este problema em específico **poderia** ser contornado da seguinte forma: ao receber um int que quero colocar em `*tabela[i]`, primeiro guardo ele em uma variável int e depois atribuo seu endereço na forma `tabela[i] = &(variavel)`. Não vejo essa solução funcionando pro lab por outros motivos ( número N é variável), mas ao menos me tirou a dúvida do erro :)

**Comment by iagoac** [comment]
Para o lab, você pode fazer uma coisa mais simples. Não é necessário que a tabela hash seja um vetor de apontadores... ela deve ser simplesmente um vetor (alocado dinamicamente, utilizando `malloc` ou `calloc`) de inteiros.  
Muitas vezes, as coisas mais simples são mais elegantes e funcionam bem 😄
