### ISSUE TITLE
Laboratórios faltantes

### ISSUE THREAD

**Issue by sayfelanjos** [iagoac/mc202#114]
Boa Tarde Professor!

Os 3 laboratórios que  ficaram para trás(laboratórios 6, 8 e 11) ainda serão cobrados ou a matéria encerra com os 9 que foram 
dados?

**Comment by enoque** [comment]
Encerra com os 9 laboratórios mesmo (@iagoac , me corrija se eu estiver errado).

**Comment by iagoac** [comment]
Sim, vamos encerrar o semestre com estes dois últimos laboratórios no dia 10 de Julho.  
Estou preparando um material adicional para quem queira praticar mais a disciplina e/ou programar algumas outras coisas. Entretanto, estes não contarão nenhum ponto para o semestre corrente.
