### ISSUE TITLE
duvida quanto a geração de arquivo "cliente.c" e "implementacao.c" no ambiente virtual. Como fazer?

### ISSUE THREAD

**Issue by alisonaran** [iagoac/mc202#115]
Olá, boa noite.
Tenho uma dúvida talvez meio "básica" demais, mas lá vai: no ambiente virtual vamos "baixando" cada lab através do terminal na pasta MC202. Em cada pasta para cada LAB é encontrando um arquivo tipo "lab01.c". Neste arquivo eu tenho a função main.
Para ter os arquivos divididos em "cliente.c" e "implementacao.c" e "interface.h" como devo fazer?
Posso usar o arquivo "LAB01.c" como cliente e criar um novo arquivo ".c" para fazer a implementacao?
Como posso fazer isso?
Estou um pouco confuso, poderiam esclarecer como trabalhar com arquivos auxiliares na maquina virtual?

Muito obrigado!

**Comment by iagoac** [comment]
@alisonaran o _makefile_ instalado no Susy compila com a seguinte linha de código: ```gcc -std=c99 -pedantic -Wall -lm -o labX *.c```.  
Desta forma, ele irá compilar todos os arquivos ```.c``` que você enviar.

O que você pode fazer é um arquivo nomeado ```lab01.c``` contendo sua função _main_ e incluindo chamadas para os cabeçalhos (arquivos ```.h```) que você possui.

Caso você consiga compilar em seu computador com esta exata chamada do ```gcc```, é bem provável que tudo ocorrerá bem também no Susy
