### ISSUE TITLE
Lab 12- Teste 3

### ISSUE THREAD

**Issue by MacavityBrazil** [iagoac/mc202#118]
Este teste diz que o segundo menor caminho custa 67, eu fiquei procurando (manualmente) qual o caminho que ele faz com este custo e o único que achei foi 0->7->4->7. Este é o caminho mesmo ou tem outro que não encontrei? Se for esse mesmo, por que não pode ser o caminho 0->7->0->7 que custaria apenas 27?

![Sem título](https://user-images.githubusercontent.com/67623581/86177765-8f2ffb00-bafd-11ea-9d12-186a312b5aaa.png)

**Comment by iagoac** [comment]
@MacavityBrazil tem uma coisa errada na sua solução, por hora.  

Um caminho mínimo, assim como o segundo caminho mínimo, não deve passar duas ou mais vezes por um único vértice.  
Desta forma, a solução 0->7->0->7 é inválida

**Comment by MacavityBrazil** [comment]
Na verdade minha solução está dando 72, porém eu não sabia qual o meu erro e fui olhar o teste e o único caminho que consegui achar que custava 67 era 0->7->4->7. Dai eu pensei se esse caminho é válido (caso seja este o tal caminho de fato), então 0->7->0->7 deveria ser válido, pois os dois passam em 7 duas vezes e usam uma mesma aresta mais de uma vez.

**Comment by iagoac** [comment]
De fato, ambas as soluções 0->7->4->7 e 0->7->0->7 são inválidas, pois elas passam duas vezes por um mesmo vértice.  

Note que, mesmo pensando na descrição do laboratório, elas não fazem sentido! É dito que DN quer chegar até o RS, andando pelo menos uma parte do caminho sozinho, sem se atrasar muito.  
Suponha a segunda solução (0->7->0->7): caso o vértice 7 represente o RS, então DN andou até lá em grupo, depois voltou a seu ponto inicial e, novamente, andou até o RS.  
O mesmo pensamento pode ser aplicado para outra solução.

**Comment by enoque** [comment]
Eu cometi um pequeno erro no código solução que acabou gerando solução inválida. Realmente essa solução é inválida. A atividade no Susy já foi atualizada, obrigado pelo feedback :)
