### ISSUE TITLE
Lab12 Testes

### ISSUE THREAD

**Issue by sayfelanjos** [iagoac/mc202#119]
Encontrei erros nos testes 3 e 4 e possivelmente nos testes de 3 à 14.
O segundo menor caminho para o teste 3 é 72 e não 67. Já no teste 4 é 107 e não 87.

**Comment by iagoac** [comment]
@sayfelanjos @MacavityBrazil vamos verificar novamente os resultados de todos os testes

**Comment by enoque** [comment]
@sayfelanjos Realmente cometi um erro no código da solução que acabou, em alguns casos, gerando soluções inválidas (como no teste 3 que realmente a solução é 72). A atividade já foi atualizada no Susy.

Porém, a solução para o teste 4 não é 107, é realmente 87. Obrigado pelo feedback :)

**Comment by sayfelanjos** [comment]
@enoque No teste 4 encontrei 3 caminhos possíveis, são eles:  0-7 = 76, 0-3-7 = 107 e 0-3-4-5-7 = 215, não enxerguei outro. Isso está certo ou eu não estou entendendo como se faz o lab12?

**Comment by MacavityBrazil** [comment]
Tem o caminho 0-6-4-2-7 que custa 87

**Comment by sayfelanjos** [comment]
@MacavityBrazil Obrigado amigo! 
Eu estava tratando o grafo como se esse fosse direcionado.
