### ISSUE TITLE
Respostas Susy lab1

### ISSUE THREAD

**Issue by Vomartins** [iagoac/mc202#12]
Fiz o lab1 e fui realizar os testes do Susy, aparetemente os arquivos de resposta estão como saída: (soma da diagonal principal) (soma da diagonal secundária) (número de colunas pares) (número de linhas ímpares). Alguém poderia conferir, por favor?

**Comment by iagoac** [comment]
@Vomartins a saída segue exatamente o que foi exposto no item *2.5 Exemplos de Saída e Entrada*. Eu acabei de conferir o código e pedi que um de meus auxiliares didáticos fizesse o mesmo, e ambos chegamos a conclusão que está tudo OK

**Comment by Vomartins** [comment]
Certo. Porém, no primeiro teste aberto temos:

5
95   |21   |93   |86   |96  --> 391
29   |67   |33   |4     |76  --> 209
47   |34   |77   |45   |82  --> 285
38   |67   |3     |19   |48  --> 175
9     |48   |1     |96   |70  --> 224

218 |237 |207 |250 |372

ou seja, a soma dos elementos de apenas uma linha é par e a soma dos elementos de duas colunas são ímpares, já no arquivo de resultados estão três linhas pares e quatro colunas ímpares.

**Comment by iagoac** [comment]
@Vomartins desculpe pela confusão.
a descrição do laboratório realmente não está refletindo o que é avaliado.
Por favor, veja a discussão em [https://github.com/iagoac/mc202/issues/13](https://github.com/iagoac/mc202/issues/13) sobre este tema

**Comment by Vomartins** [comment]
Tudo certo, obrigado.
