### ISSUE TITLE
Erro 139 no Lab 10

### ISSUE THREAD

**Issue by cami-sh** [iagoac/mc202#123]
Boa noite :)

Estou fazendo o lab 10 e o resultado está dando correto para os testes do 1 ao 11, mas do 12 ao 15 está dando erro de processamento (139) 😢 

Há algo de especial com estes testes?

Não sei se estou deixando de considerar alguma coisa, mas acredito que não estou acessando mais memória do que aloquei.

**Comment by leo-leao** [comment]
Esses testes tem o diferencial de serem bem grandes

**Comment by iagoac** [comment]
@cami-sh é exatamente o que o @leo-leao comentou.  
Provavelmente você está utilizando alguma estruturas de dados inadequada ou alocando memória desnecessária.

Estes testes grandes servem justamente para forçar todos a implementarem estruturas de dados mais eficientes, tanto em consumo de memória como em tempo de execução.

**Comment by enoque** [comment]
Caso esteja utilizando recursão, ela pode (provavelmente vai) causar um problema.

**Comment by cami-sh** [comment]
Hum, entendi. Criei a tabela hash como um vetor alocado dinamicamente (usei malloc), isso está correto?

Estou utilizando recursão mesmo, vou tentar pensar em outra maneira... Obrigada!

**Comment by cami-sh** [comment]
Consegui fazer!! Obrigada pela ajuda ❤️
