### ISSUE TITLE
Dúvida sobre fim do semestre e quantidade de Labs

### ISSUE THREAD

**Issue by RPanosso** [iagoac/mc202#126]
Gostaria de saber se terá algum lab além do 12 (ultimo colocado)? Além disso, até quando pode ser entregue os labs atrasados?

**Comment by cami-sh** [comment]
O prof comentou sobre isso na #114 :)
Entendi também que os labs podem ser entregues até dia 10

**Comment by RPanosso** [comment]
Obrigadoo :)

**Comment by cami-sh** [comment]
Maginaa
