### ISSUE TITLE
Lab 12 - Entrega

### ISSUE THREAD

**Issue by wellingtondiaspereira** [iagoac/mc202#127]
Estou tendo bastante dificuldade em completar o lab 12, e não estou conseguindo implementar um algoritmo que seja eficiente para resolver o problema. 

Gostaria de saber se seria possível adiar a entrega do lab 12 por alguns dias?

**Comment by Alandroid** [comment]
Seria muito bom! E inclusive acho que o pessoal como um todo está tendo dificuldades em montar esse algoritmo, dado o número baixo de submissões corretas até hoje

**Comment by Antonio-Silvestre** [comment]
Nossa, mais alguns dias pra entregar esse lab ajudariam muito! 
Eu ia pedir a mesma coisa, mas o @wellingtondiaspereira foi mais rápido rsrs

**Comment by leticia-rosa** [comment]
Também acho que seria muito bom pois também estou tendo dificuldades com esse algoritmo!

**Comment by lucas-vecina** [comment]
Também gostaria que prorrogassem a entrega. Fiz quase 200 linhas e na hora de submeter descobri que eles queriam um grafo não-direcionado (fiz direcionado). Basicamente vou ter que recomeçar quase do zero. Uns dias a mais seriam ótimos mesmo.

**Comment by enoque** [comment]
@lucas-vecina , por que? Um grafo não-direcionado é basicamente um grafo direcionado com aresta indo e voltando. Se você adicionou a aresta (u,v), basta adicionar a aresta (v,u) com o mesmo peso e seguir o algoritmo. Só muda uma linha na hora da entrada.

**Comment by lucas-vecina** [comment]
@enoque Hmm, isso daria certo mesmo eu tendo feito por lista de adjacência? Basicamente eu iria dobrar o número de "nós" na minha lista ligada dessa maneira, não é?

**Comment by enoque** [comment]
Daria certo sim. Inclusive, é dessa forma que normalmente é feito. Se você pensar bem, uma aresta sem direção, é basicamente duas arestas direcionadas com pesos iguais.

**Comment by lucas-vecina** [comment]
@enoque Obrigado pela dica. Vou fazer algumas alterações no meu código nesse sentido e ver se funciona.

**Comment by vinicmelicio** [comment]
Adiar esse lab de fato ajudaria muito!

**Comment by iagoac** [comment]
Este laboratório realmente está um pouco mais difícil que os demais dados durante o semestre.  

Vou tomar as seguintes atitudes então:  
1. Adiar o laboratório 12 para o dia 17/07 às 23h59
2. Extender a data de entrega de todos os outros labs para o dia 17/07 às 23h59

Note que isto implica que não vou alterar a data original de entrega do laboratório sobre hash. Este poderá ser entregue normalmente até dia 10/07 as 23h59 e até dia 17/07, no mesmo horário, em atraso.

**Comment by iagoac** [comment]
Só uma observação: para que eu possa fazer isto, a submissão do laboratório de hashes ficará indisponível na madrugada de sexta para sábado e na manhã de sábado para que eu possa coletar as submissões de todos. Logo após, ela será reaberta

**Comment by RPanosso** [comment]
@iagoac com isso também a atualização da planilha das notas vai ficar para o dia 17/07?

**Comment by iagoac** [comment]
@RPanosso hoje eu vou atualizar com as notas do laboratório de hashes.  
Mas a atualização das entregas atrasadas vai ficar pro dia 17

**Comment by marinabmorais** [comment]
@iagoac a gente vai poder entregar o lab 12 atrasado? depois do dia 17?

**Comment by iagoac** [comment]
@m-abi não
