### ISSUE TITLE
Lab 7 (Nota)

### ISSUE THREAD

**Issue by LuccasBastos** [iagoac/mc202#128]
Boa tarde professor, tudo bem?

Gostaria de saber sobre o laboratório 7, eu consegui fazer a entrega a tempo, porém, obtive 2 erros de processamento em 2 testes diferentes. A nota referente a esse lab seria o total de testes corretos pelo numero total (no caso, 13/15) ou ficaria em 0 por não ter conseguido completar totalmente os testes?

**Comment by iagoac** [comment]
@LuccasBastos todas as notas dos laboratórios foram binárias, isto é, total no caso de sucesso em todos os testes e zero em caso de alguma falha.
