### ISSUE TITLE
Lab 12 - Dificuldade de implementação

### ISSUE THREAD

**Issue by cahr118** [iagoac/mc202#129]
Bom dia, professor! Estou com dificuldade de enxergar como eu faria pra conseguir obter o segundo caminho mais curto para o RS... Eu implementei o Dijkstra e algumas funções auxiliares pra calcular a distância correta, a partir do menor caminho encontrado usando o Dijsktra. Isso está funcionando certinho, porém o enunciado do laboratório se refere ao segundo menor caminho que poderia ser obtido e, não consegui realizar de forma efetiva, modificações no meu algoritmo do Dijkstra pra pular ou remover as arestas que se referem ao primeiro menor caminho encontrado. Até tentei usar uma solução de Backtracking pra isso :/ Vocês teriam alguma dica ou algum material que poderia me ajudar com isso? Agradeço desde já :)

**Comment by iagoac** [comment]
@cahr118 temos algumas discussões sobre este assunto já aqui no github.  

Você está certa em utilizar uma modificação do algoritmo de Dijkstra. O segundo menor caminho pode ser obtido com pequenas modificações/adições a este algoritmo.

---

> (...) modificações no meu algoritmo do Dijkstra pra pular ou remover as arestas que se referem ao primeiro menor caminho encontrado

Você também está pensando corretamente. Remover arestas do caminho mais curto e rodar novamente o Dijkstra é uma boa forma de solucionar este problema.

---

Também existem dois algoritmos da década de 70 que encontram os _k_ menores caminhos entre dois vértices de um grafo:  
1. [D. Eppstein, “Finding the k shortest paths,” SIAM J. Comput., vol. 28, no. 2, pp.652–673, Feb. 1999](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.39.3901&rep=rep1&type=pdf)
2. [J. Y. Yen, “Finding the K Shortest Loopless Paths in a Network,” Management Science, vol. 17, no. 11, pp. 712–716, 1971](https://doi.org/10.1287%2Fmnsc.17.11.712)

Você pode procurar informações sobre estes dois algoritmos para ter uma ideia de como funcionam e/ou tentar implementa-los. Entretanto, isto é uma tarefa bem mais complexa e penosa do que a estratégia que você está atualmente seguindo.

**Comment by cahr118** [comment]
Muito obrigado pelas informações, professor! Tentarei analisar melhor a minha solução e olharei essas outras duas que comentou, caso sejam necessárias. :)
