### ISSUE TITLE
Entendimento do enunciado

### ISSUE THREAD

**Issue by karimmbk** [iagoac/mc202#13]
Boa noite,
"Quantas linhas possuem uma soma com valor par", ficou vago essa explicação para mim, não consegue entender muito bem. É  para contabilizar a quantidade de linhas que a soma de todos os elementos da linha tem que dar par? Precisa ter pelo menos uma soma par na linha dos elementos? Tem que ter apenas uma soma? Queria entender melhor que ficou um pouco vago para mim essa explicação

**Comment by iagoac** [comment]
@karimmbk é para contabilizar a quantidade de linhas que a soma de todos os elementos da linha é par. A mesma coisa para a coluna ímpar

**Comment by karimmbk** [comment]
obrigado!

**Comment by karimmbk** [comment]
@iagoac 
```
5
95 21 93 86 96 = 391
29 67 33 4 76 = 209
47 34 77 45 82 = 285
38 67 3 19 48 = 175
9 48 1 96 70 = 224
```
`resposta: 328 253 3 4`

A resposta não parece coerente com o que vc me falou professor, somando as linhas têm: 1 linha par e 4 ímpares

**Comment by karimmbk** [comment]
@iagoac pelo q eu percebi aqui foi trocado no enunciado, as repostas estão invertidas. Os valores estão dando as somas das colunas pares e linhas ímpares.

```
Compilando o programa...
Executando os testes...
arq01.in    OK          
arq02.in    OK          
arq03.in    OK          
arq04.in    OK          
arq05.in    OK          
arq06.in    OK          

Total de erros encontrados: 0
```
Testei assim e meu código passou

**Comment by iagoac** [comment]
@karimmbk acredito que você realmente tenha razão.
Vou atualizar a descrição do laboratório para incorporar esta mudança.
Por favor, não feche este _issue_

**Comment by karimmbk** [comment]
Sem problemas! Outras coisa que percebi eh a ordem de impressão. Que eh: `soma da diagonal principal, soma da secundaria , colunas com soma par e linhas com soma ímpar.`
Além disso, um problema que pode surgir é a falta do  "\n" no printf, o printf dos resultados estão sem, isso vai dar uma diferença no diff entre os arquivos respostas e os prints das saídas dos laboratórios dos alunos

**Comment by iagoac** [comment]
Sim, eu notei isto também.
Vou atualizar o PDF com esta descrição.

Quanto ao "\n", está descrito no PDF que ele não deve ser inserido no output do código.

**Comment by enoque** [comment]
Eu acabei chamando o que era coluna de linha e o que era linha de coluna (puro bug da minha cabeça), perdão =/

Dei uma atualizada no PDF melhorando um pouco a descrição e arrumando esse erro. Obrigado pelo feedback :)
