### ISSUE TITLE
Lab 12 - Falha no Último Teste Fechado

### ISSUE THREAD

**Issue by dedsylva** [iagoac/mc202#130]
Olá professor, estou tendo dificuldade com o último teste fechado do lab 12. Eu já tentei mudar de várias maneiras a lógica do algoritmo, mas não consegui, continua dando erro de processamento : tempo máximo de processamento excedido (código 137).
Gostaria de saber se ele é muito longo ou se é um caso especial que não estou considerando.

**Comment by enoque** [comment]
Você usou fila de prioridade? Na verdade os teste não são tão longos assim não, dei uma maneirada nos tamanhos deles.

**Comment by dedsylva** [comment]
Usei sim. Tentei fazer um heapsort cada iteração pra ver se melhorava a complexidade da função de extrair mínimo. Pode ser um caso que não estou considerando então? Esse erro também e gerado se o codigo fica em loop eterno?
