### ISSUE TITLE
Lab10 hash

### ISSUE THREAD

**Issue by alisonaran** [iagoac/mc202#131]
Oi, boa noite.
No lab10 consegui fazer o hash parcialmente, pois quando há repetição de resto ele dá erro. Alguma ideia de como tratar o caso de repetição de resultado? (exemplo: 14 %10 = 4 preenche o a[4], se depois tem 24 %10 = 4, ele nao vai pro a[5]...)
Poderia dar alguma dica?
Obrigado.

**Comment by enoque** [comment]
Não sei como está implementando, mas agora provavelmente é só um erro de implementação mesmo. Minha dica é bem simples: faça uma função que dada uma chave, retorne qual a posição mais próxima (sabendo que só existe movimento em sentido horário) livre que a chave se encaixa. Tendo isso implementado, basta chamar essa função para a chave e chamar a função de inserir na posição correta.

**Comment by alisonaran** [comment]
Oi, tudo bem?
Te mandei o codigo por e-mail, pois entendo que já estou fazendo dessa forma.
Claro que estou errando algo, mas sinceramente não consigo achar onde.
Poderia olhar pra mim por favor? Me ajudaria demais!!!

Obrigado.
