### ISSUE TITLE
Dificuldade para acessar o Susy

### ISSUE THREAD

**Issue by RPanosso** [iagoac/mc202#133]
Estou tentando acessar o susy para submeter o Lab12, porém ele não esta carregando, nem pelo celular nem pelo computador

**Comment by victorpmacc** [comment]
Também não consigo acessar daqui, deve estar fora do ar... O ruim é que não dá para baixar os testes pelo terminal :(

**Comment by iagoac** [comment]
Parece que houve uma instabilidade mais cedo.  
Entretanto, também já me parece que foi resolvida.

Como ela durou pouco, não considero que isto tenha afetado a submissão de nenhum laboratório.
