### ISSUE TITLE
Código 137 no teste 15 da tarefa 10

### ISSUE THREAD

**Issue by l221215** [iagoac/mc202#134]
Professor por gentileza, você poderia me elucidar um pouco em relação o que significa o erro de código 137 e possíveis soluções. O resto dos testes estão corretos.
Agradeço pela atenção

**Comment by iagoac** [comment]
@l221215 existe uma pergunta duplicada sobre este tema aqui no Github. Vou fechar esta sua pergunta e vamos concentrar nossas discussões [aqui](https://github.com/iagoac/mc202/issues/130)
