### ISSUE TITLE
Lab 12 - Máximo de Submissões

### ISSUE THREAD

**Issue by czariv** [iagoac/mc202#135]
Queria saber se é possível que, junto do adiamento da entrega, o senhor aumentasse também o número máximo de submissões.

**Comment by iagoac** [comment]
@czariv dupliquei o número de submissões

**Comment by czariv** [comment]
professor quando eu tentei mandar novamente o meu lab deu a mesma mensagem:
Excedido o número máximo 20 de submissões:
NoneType: None

**Comment by iagoac** [comment]
Olá @czariv eu verifiquei novamente no Susy e está contando 30 submissões

![image](https://user-images.githubusercontent.com/8388583/87841014-d39af500-c878-11ea-9b25-4ce10c82d4cd.png)
