### ISSUE TITLE
tabela de Hash: duvida de como pular para a casa "zero" quando chegar no fim do vetor

### ISSUE THREAD

**Issue by alisonaran** [iagoac/mc202#137]
Oi, boa noite.
Ainda tenho problemas no lab do hash. Basicamente, faço o seguinte: leio N, leio os "N" valores num vetor v1, faço uma função hash que devolve o resto e tento fazer uma funcao que insere os valores de v1 em um outro vetor v2 (iniciado com valores "-1") de acordo com o resultado do hash (para depois fazer um _for_ percorrendo os vetores com esta funcao), e é na função que insere que esta o meu problema: não consigo fazer a inserção circular e reiniciar quando acaba o tamanho do vetor. Já tentei diversas coisas: fiz de um jeito, recomecei, fiz de outro, recomecei de novo... 
Por exemplo, vejam duas tentativas de inserir:
1)numa primeira o problema surge quando precisa retornar ao inicio do vetor
![image](https://user-images.githubusercontent.com/63574450/87381906-21a7b400-c56c-11ea-8671-580bde178af1.png)

2)numa outra o problema é que está sobreescrevendo o resultado (o item não "pula" pra vaga da frente):
![image](https://user-images.githubusercontent.com/63574450/87381957-41d77300-c56c-11ea-9d0d-1b887942341f.png)

Por favor, poderiam me ajudar nesta resolução?
Entendo que o problema é voltar ao item 0 do vetor e continuar guardando os valores. Não estou sabendo fazer isto. Não sei se estou usando vetor errado, se não estou fazendo restrições corretamente...
Enviarei todos os códigos que tentei por e-mail para maior esclarecimento, explico tudo que fiz... só me dar o endereço. Se achar melhor e puderem me receberem aí em Campinas, vou aí na mesma hora. Mas quero muito resolver este problema.

Desde já agradeço muito!

**Comment by enoque** [comment]
Acho que você tá complicando bem mais do que devia... Conhece a função modulo e seu funcionamento? Uma verdade sobre essa função é que da um valor X modulo N, todos os resultados possíveis estão entre 0 e n-1. Outra coisa interessante é que ela é "bem comportada". 

O modulo(X, N) = modulo(X+1, N)+1, tirando os casos de borda que são quando modulo(X) é igual N-1, que nesse caso, modulo(X+1, N) = 0. Caso você não faça ideia do que eu esteja falando, recomendo pesquisar um pouco sobre as funções modulares. 

Após tudo isso, um jeito bem simples de resolver esse problema é:

`i = (i+1)%n`

Onde n é o tamanho do vetor. Assim, a variável i sempre vai está numa posição válida e sempre vai está onde você quer.

**Comment by alisonaran** [comment]
Obrigado Enoque!
Realmente estava complicando a toa.
Consegui resolver.
Obrigado!
