### ISSUE TITLE
lab10 falha de execução

### ISSUE THREAD

**Issue by LuisNascimento11** [iagoac/mc202#138]
Olá professor, no lab10, eu enviei o código sem uma \n no final, quando eu corrijo o lab com o \n, dá erro de processamento

**Comment by iagoac** [comment]
Essa é nova para mim!  

Infelizmente, sem ver código nenhum, fica complicado de te ajudar.  
Não me vem nenhum erro clássico na cabeça que pode estar originando este comportamento

**Comment by Tomikins** [comment]
não seria falta de alguma biblioteca? stdlib.h ou stdio.h?

**Comment by iagoac** [comment]
@Tomikins ele consegue usar o ```printf```, mas o ```\n``` está falhando.  
Caso fosse falta do ```stdio.h```, ele não conseguiria usar o ```printf``` em momento algum

**Comment by LuisNascimento11** [comment]
Era erro com a IDE, o main estava vindo com return 1 como padrão
