### ISSUE TITLE
Erros no lab12

### ISSUE THREAD

**Issue by eduarda-nicoletto** [iagoac/mc202#139]
Eu terminei hoje meu lab12 mas estou com um problema de segmentation fault. Já tive esse problema em outros momentos mas sempre consegui consertar. Dessa vez, meu programa imprime a resposta correta para os casos do enunciado e para os dois primeiros casos do SuSy, mas quando chega no terceiro, todos dão erro 139.

Pra tentar resolver esse problema, fui em algumas monitorias que me ajudaram muito, mas esse último erro não consegui resolver. Tentei colocar printf em um monte de lugar no código, mas quando compilo, nada é impresso, vai diretamente para segmentation fault.

Estou sem ideias do que fazer. Alguém saberia ajudar?

**Comment by iagoac** [comment]
@eduarda-nicoletto com estas poucas informações que você me deu, fica difícil de te ajudar.  
Como você diz que nada é impresso, a única coisa que posso dizer é que você provavelmente tem algum erro no momento de alocação de suas variáveis.

Uma outra coisa que você também pode fazer é utilizar o _valgrind_ para debugar seu código

**Comment by eduarda-nicoletto** [comment]
Nunca usei o valgrind mas vou tentar hoje. Vou deixar meu código aqui também caso tenha alguma sugestão. Valeu!!
(Aqui estão vários prints para conferir minha resposta também)

#include <stdio.h>
#include <stdlib.h>

//DEFINIÇÃO DE FILA DE PRIORIDADE E SEUS ITENS
typedef struct{
    int local, chave; //vertices, prioridades
}Item;

typedef struct{
    Item *fila; //vetor de itens
    int *index; //indice do vertice em fila
    int qtd, tamanho; //qtd de elementos, tamanho
}FilaP;
typedef FilaP *p_fp;

//CRIANDO FILA DE PRIORIDADES
p_fp criar_fila(int sz){
printf("C0");
    p_fp FP=malloc(sizeof(FilaP));
    FP->fila=malloc(sz*sizeof(Item));
    FP->index=malloc(sz*sizeof(int));
    FP->qtd=0; FP->tamanho=sz;
    return FP;
}

//INSERINDO ITENS NA FILA DE PRIORIDADES
#define pai(i) (i-1)/2
void up_heap(p_fp f, int n){
printf("C1");
    Item aux;
    if(n>0 && f->fila[pai(n)].chave > f->fila[n].chave){ //é menor e deve subir
        aux=f->fila[n];                  
        f->fila[n]=f->fila[pai(n)];     f->index[f->fila[n].local]=n;
        f->fila[pai(n)]=aux;            f->index[f->fila[pai(n)].local]=pai(n);
        up_heap(f, pai(n));
    }
}
void insere_fila(p_fp FP, int i, int j){ //Heap de mínimo
printf("C2");
    Item x;
    x.local=i;
    x.chave=j;
    FP->fila[FP->qtd]=x;
    FP->index[i]=FP->qtd;
    FP->qtd++;
    up_heap(FP,(FP->qtd)-1);
}

//EXTRAINDO O MÍNIMO DA FILA DE PRIORIDADES
#define esq(i) (2*i +1)
#define dir(i) (2*i +2)
void desce_heap(p_fp f, int n){
printf("C3");
    int minf;
    Item aux;
    if(esq(n)<(f->qtd)){ //Existe filho esquerdo?
        minf=esq(n); //Existe e chutamos que ele é o menor.
        
        if(dir(n)<(f->qtd) //Existe filho direito?
        && f->fila[esq(n)].chave>f->fila[dir(n)].chave) //Se sim, ele é menor que o esquerdo?
            minf=dir(n); //O filho direito tem menor prioridade que o esquerdo
            
        if(f->fila[n].chave>f->fila[minf].chave){ //Temos o menor dos filhos. Ele é menor que o pai?
            aux=f->fila[n]; //Sim, trocamos ele com seu pai
            f->fila[n]=f->fila[minf];   f->index[f->fila[n].local]=n;
            f->fila[minf]=aux;          f->index[f->fila[minf].local]=minf;
            desce_heap(f, minf);
        }
    }
}

Item min(p_fp f){ //Trocamos o item mínimo com o último
printf("C4");
    Item aux=f->fila[0];
    f->fila[0]=f->fila[(f->qtd)-1];     f->index[f->fila[0].local]=0;
    f->fila[(f->qtd)-1]=aux;            f->index[f->fila[(f->qtd)-1].local]=(f->qtd)-1;
    f->qtd--; //Tiramos ele da qtd de itens
    desce_heap(f, 0); //Descemos na árvore
    return aux; //Retornamos o item mínimo
}

//FUNÇÃO QUE RETORNA PRIORIDADE
int prioridade(p_fp f, int vertice){
printf("C5");
    int i; //Posição em fila que está o vértice
    i=f->index[vertice];
    return f->fila[i].chave;
}

//DEFINIÇÃO DE GRAFO E SEUS NÓS
typedef struct Noh{
    int local, tempo; //vertices, pesos
    struct Noh *vizinho; //prox
}Noh;
typedef struct Noh *p_no;

typedef struct{
    p_no *mapa; //matriz de adjacencia
    int sz; //tamanho da matriz
}Grafo;
typedef Grafo *p_grafo;

//CRIANDO GRAFO
p_grafo criar_grafo(int tamanho){
printf("B0");
    p_grafo grafo;
    grafo=malloc(sizeof(Grafo));
    grafo->sz=tamanho;
    grafo->mapa=calloc(tamanho,sizeof(Noh));
    return grafo;
}

//INSERINDO ARESTA NO GRAFO
p_no insere_vizinhos(p_no lista, int z, int peso){
printf("B1");
    p_no novo=malloc(sizeof(Noh));
    novo->vizinho=lista;
    novo->local=z;
    novo->tempo=peso;
    return novo;
}
void insere_aresta(p_grafo g, int x, int y, int peso){
    g->mapa[x]=insere_vizinhos(g->mapa[x], y, peso);
    g->mapa[y]=insere_vizinhos(g->mapa[y], x, peso);
}

//REMOVENDO ARESTAS DO GRAFO
p_no remove_viz(p_no vizinhos, int vertice){
printf("B2");
    p_no prox;
    if(vizinhos==NULL){
        return NULL;
    }else if(vizinhos->local!=vertice){
        vizinhos->vizinho=remove_viz(vizinhos->vizinho,vertice);
        return vizinhos;
    }else{ //vizinhos->local==vertice, vamos remover
        prox=vizinhos->vizinho;
        free(vizinhos);
        return prox;
    }
}
void remove_aresta(p_grafo g, int x, int y){
    g->mapa[x]=remove_viz(g->mapa[x], y);
    g->mapa[y]=remove_viz(g->mapa[y], x);
}

//DESTRUINDO GRAFO
void libera_vizinhos(p_no lista){
    if(lista!=NULL){
        libera_vizinhos(lista->vizinho);
        free(lista);
    }
}
void destroi(p_grafo g){
printf("B3");
    int i;
    for(i=0; i<g->sz; i++)
        libera_vizinhos(g->mapa[i]);
    free(g->mapa);
    free(g);
}

//ACHANDO CAMINHO MÍNIMO (DIJKSTRA)
#define infinito 214748369
int* caminho_min(p_grafo g){
printf("A0");
    int i,*pais=malloc((g->sz)*sizeof(int)); //Conterá o caminho
    p_no j; //Auxiliar
    Item aux; //Auxiliar
    p_fp heap=criar_fila(g->sz); //Heap mínimo
printf("A1");    
    for(i=0; i<g->sz; i++){
        pais[i]=-42; //Ninguém tem pai, a princípio
        insere_fila(heap, i, infinito); //Insiro todos os vértices no heap com peso infinito
    }
    pais[0]=0; //Sempre saio do mesmo lugar, zero
    heap->fila[heap->index[0]].chave=0; //É o lugar de partida, o mais longe, sua prioridade (chave) é zero
printf("A2");    
    while(heap!=NULL && heap->qtd!=0){
        aux=min(heap); //Item mínimo do heap (caminho de menor distância)
        i=aux.local; //Vértice do item mínimo
        
        if(aux.chave!=infinito) //Ele não está a distância infinita, vai ser o próximo da franja
            for(j=g->mapa[i]; j!=NULL; j=j->vizinho) //Percorre os vizinhos na franja, i já parte da árvore
                if( prioridade(heap,i)+j->tempo < prioridade(heap,j->local) ){
                //Se sim, esse é o melhor caminho que eu conheço agora
                    heap->fila[heap->index[j->local]].chave=prioridade(heap,i)+j->tempo; //Diminuo a prioridade
                    pais[j->local]=i; //Atualizo o pai
                }        
    }
printf("A3");
    return pais;
}

//CALCULANDO O TEMPO LEVADO PARA PERCORRER O CAMINHO MÍNIMO
int tempo(int *p, int **mtx, int n){
    int i, tempo=0;
    for(i=n-1; i!=0; i=p[i])
        tempo=tempo+mtx[i][p[i]];
    return tempo; 
}


//CALCULANDO QUANTAS ARESTAS TEM NO CAMINHO MÍNIMO
int n_arestas(int *p, int **mtx, int n){
    int i, tempo;
    for(i=1; i<n; i++){
        if(p[i]==0){
            tempo=i;
            break;
        }
    }
    return tempo+1; 
}

/************************************CÓDIGO************************************/
int main(){
    int n,m;
    p_grafo unicamp;
    int i,j,k,l, temp, tempo1, tempo2;
    int *pais, *aux, **matriz;

/*LENDO ENTRADA E CRIANDO GRAFO*/
printf("A");
scanf("%d %d",&n,&m); //Leio a primeira linha
printf("B");
unicamp=criar_grafo(n); //Crio o grafo que tem o mapa da unicamp
printf("C");
matriz=calloc(n,sizeof(int)); //Crio uma matriz de adjacência também para auxiliar
for(i=0; i<n; i++) matriz[i]=calloc(n,sizeof(int));
printf("D");
for(i=0; i<m; i++){
    scanf("%d %d %d",&j,&k,&l);
printf("E");
    insere_aresta(unicamp,j,k,l); //Insiro arestas no mapa da unicamp
printf("F");
    matriz[j][k]=l; //Insiro arestas na matriz de adjacência
    matriz[k][j]=l;
printf("G");
}

/*ACHANDO O CAMINHO MÍNIMO E O SEGUNDO CAMINHO MÍNIMO*/
printf("H");
pais=caminho_min(unicamp); //Encontro o menor caminho para o RS
printf("I");

for(i=0; i<n; i++)
printf("%d ",pais[i]);
temp=tempo(pais,matriz,n);
printf("\n%d\n",temp);

tempo2=infinito;
j=n-1;  //Achando os segundos caminhos mínimos
for(i=0; i<n_arestas(pais,matriz,n); i++){
    remove_aresta(unicamp,j,pais[j]); //Removendo as arestas
    aux=caminho_min(unicamp); //Acho um segundo caminho mínimo
    tempo1=tempo(aux,matriz,n);
	printf("tempo1 %d\n",tempo1);
    if(tempo1<tempo2 && tempo1>temp) //Acho o novo tempo mínimo
        tempo2=tempo1;
    insere_aresta(unicamp,j,pais[j],matriz[j][pais[j]]); //Retornamos as arestas
    j=pais[j];
}

/*ACHANDO O SEGUNDO MENOR CAMINHO MÍNIMO*/
//printf("%d\n",tempo2); //imprimimos a saída
destroi(unicamp); //encerra o código

    return 0;
}

**Comment by eduarda-nicoletto** [comment]
@iagoac 
Usando um debugger online, eu descobri que o segmentation fault acontece quando estou preenchendo a matriz de adjacência. Só para explicar, eu usei lista ligada para o grafo, mas também usei a matriz de adjacências como auxiliar para que no main seja mais fácil de acessar o tempo de percurso entre dois vértices.

Tem alguma forma de concertar isso ou devo eliminar a matriz e usar apenas o grafo para achar o tempo?

**Comment by iagoac** [comment]
@eduarda-nicoletto vou apagar sua última mensagem, pois não se deve colocar o código inteiro do laboratório desta forma aqui no Github. Assim, qualquer outro colega seu pode pegar e copiar seu código, o que será mostrado no detector de plágios.

Olhando seu código, eu consegui identificar alguns erros. Por exemplo, nas linhas
```
FP->fila=malloc(szsizeof(Item));
FP->index=malloc(szsizeof(int));
```
você não multiplicou ```sz``` pelo ```sizeof```. É muito estranho para mim que isto não tenha acarretado nenhum erro de compilação.

Sua função ```p_no insere_vizinhos(p_no lista, int z, int peso)``` também está muito estranha, pois ela recebe um ```p_no``` como argumento e retorna outro ```p_no``` que, essencialmente, são os mesmos.

---

> Tem alguma forma de concertar isso ou devo eliminar a matriz e usar apenas o grafo para achar o tempo?

Forma de concertar até tem. Mas utilizar duas estruturas de dados diferentes fica um pouco confuso... Acredito que seja melhor utilizar somente uma como forma de evitar erros e bugs no código.

**Comment by eduarda-nicoletto** [comment]
> vou apagar sua última mensagem, pois não se deve colocar o código inteiro do laboratório desta forma aqui no Github. Assim, qualquer outro colega seu pode pegar e copiar seu código, o que será mostrado no detector de plágios.

Perdão, professor!! Quando começa a chegar o prazo de entrega, o cérebro vai ficando sem noção.
Quanto a função insere_vizinhos, fiz similar ao dos slides. Não entendo o que poderia estar errado nela, me parece fazer sentido.

Vou trabalhar em cima desses erros que você comentou. Obrigada!

**Comment by eduarda-nicoletto** [comment]
@iagoac Consegui resolver os problemas e inclusive removi a matriz e algumas funções desnecessárias, mas agora o resultado dos testes abertos 7, 8, 10 dão errado. Alguma ideia do que pode ser? Todos são valores pouco acima do esperado

**Comment by iagoac** [comment]
@eduarda-nicoletto bem, provavelmente seu algoritmo ainda está errado 😭   
Infelizmente, eu não vejo uma característica específica que estes três testes compartilhem para poder te ajudar assim
