### ISSUE TITLE
Lab 1

### ISSUE THREAD

**Issue by Hunterms** [iagoac/mc202#14]
Professor, no resultado pedido pelo susy nos teste, creio que tenha algo errado. No teste 1, por exemplo:
5
95 21 93 86 96 
29 67 33 4 76 
47 34 77 45 82 
38 67 3 19 48 
9 48 1 96 70 

só a ultima linha tem soma par, mas o resultado do susy diz que há 3 linhas com soma par.
você poderia verificar, por favor?

**Comment by iagoac** [comment]
@Hunterms a descrição do laboratório realmente não está refletindo o que é avaliado.

Por favor, veja a discussão em [https://github.com/iagoac/mc202/issues/13](https://github.com/iagoac/mc202/issues/13) sobre este tema
