### ISSUE TITLE
correção LAB09

### ISSUE THREAD

**Issue by alisonaran** [iagoac/mc202#142]
Caros @iagoac e @enoque , boa tarde!
No LAB09 meu codigo compilou certinho e para os 10 testes abertos o resultado foi correto.
Quando fui para o Susy, os primeiros 3 testes fechados deram ok, mas os dois ultimos deram incorreto por tempo de processamento. Ou seja, de 15 testes deu certo em 13...
Por favor, poderia neste caso fazer uma correção do meu lab? Se eu tirar 6 nele eu acredito que passo na matéria... Mas se a nota for "fechada" em 0, aí complica pra mim. Provavelmente é algum erro que eu poderia ter evitado, mas não encontrei. Agradeço demais se analisar este caso.
No susy voces poderão ver que os 13 primeiros testes deram correto, mas . Vejam como os testes abertos deram ok:

![image](https://user-images.githubusercontent.com/63574450/87883165-f42f9000-c9db-11ea-92cc-000d0db04cdf.png)

![image](https://user-images.githubusercontent.com/63574450/87883264-8a63b600-c9dc-11ea-90a9-051c492eb035.png)

Por favor, poderiam ver este caso? Obrigado!

**Comment by RPanosso** [comment]
O meu ocorreu a mesma coisa, porém foi apenas no teste 15, também fechado e também não consegui achar o problema no meu programa... :/
