### ISSUE TITLE
Notas finais

### ISSUE THREAD

**Issue by Hunterms** [iagoac/mc202#143]
As notas finais são aquelas porcentagens? 
Então se a porcentagem for maior que 50% a nota é  porcentagem/10?
Tipo 100% = 100/10 = 10?

**Comment by iagoac** [comment]
Exatamente isso @Hunterms.

Quem tirou 50% (neste caso, 5) ou mais está aprovado.  
Quem tirou entre 25% e e 49.9% poderá optar por realizar o exame final.

**Comment by alisonaran** [comment]
@iagoac , bom dia!
Já temos uma data ou formato definido para o exame?
Obrigado!

**Comment by iagoac** [comment]
@alisonaran acabei de postar [aqui](https://github.com/iagoac/mc202/issues/144)
