### ISSUE TITLE
Exame final

### ISSUE THREAD

**Issue by iagoac** [iagoac/mc202#144]
O exame final acontecerá no dia 27 de Agosto âs 19h. Todos os alunos que obtiveram uma nota igual ou superior a 25% e inferior a 50% poderão optar por realizar o exame final ou não. 

O exame será uma prova com quatro ou cinco questões e o tempo de resolução será de duas horas.
Duas diferentes provas serão disponibilizadas no página da disciplina exatamente âs 18h55 do mesmo dia. Alunos cujo último número do RA seja impar deverão fazer a prova um, enquanto alunos cujo último número do RA seja par deverão fazer a prova dois.

A prova deverá ser resolvida a lapis ou a caneta e, posteriormente, fotografada e enviada por email para mim até o prazo limite de 21h20. Desta forma, existe um prazo de 20 minutos para que vocês fotografem a prova e a enviem por e-mail após sua finalização.

O e-mail deverá conter os seguintes dados:  
1. **Nome completo**
2. **RA** 
3. **Turma** (D, E, F ou G) 
4. **Fotos da prova em anexo** (formato .zip ou diversas fotografias em sequência)

O principal material de estudos para a prova será o livro "ProjetodeAlgoritmosCom Implementaçõesem Pascal e C", quarta edição, do professor Nívio Ziviani, capítulos 2, 3 e 4. Desta forma, não será cobrado nada de Grafos no exame final.

Como provavelmente ninguém possui acesso a este livro ou a biblioteca da UNICAMP, vocês podem acessar o livro no seguinte link.

[http://clip2net.com/clip/m1076/1206625061-ebook-projetos-de-algoritmos-com-implementazhes-em-pascal-e-c-nivio-ziviani-4ed-3618kb.pdf](http://clip2net.com/clip/m1076/1206625061-ebook-projetos-de-algoritmos-com-implementazhes-em-pascal-e-c-nivio-ziviani-4ed-3618kb.pdf)

É de sua inteira responsabilidade garantir que as fotos da prova tenham uma boa resolução, de tal forma que seja legível a qualquer pessoa que abra o arquivo.

Por favor, pratiquem uma ou duas vezes nesta semana como tirar uma foto nítida e em boa resolução de uma folha e como enviar a mesma por e-mail no prazo de 20 minutos.

Caso exista alguma dúvida, por favor, responder a esta thread

**Comment by RPanosso** [comment]
Professor, as notas ainda não foram computadas no sistema da DAC? Pq para mim a matéria ainda está em aberto no simulação da integralização

**Comment by iagoac** [comment]
@RPanosso estou com problemas para acessar o sistema do DAC.  
Estou em contato com a secretaria para regularizar meu acesso e lançar as notas.

**Comment by RPanosso** [comment]
Ok, obrigado

**Comment by alisonaran** [comment]
Professor @iagoac , tudo bem?
Como será o exame? Serão questões teóricas ou práticas? Poderia dar uma dica? Obrigado!

**Comment by iagoac** [comment]
@alisonaran as questões serão praticamente todas teóricas.  

Estou finalizando a prova agora. Entretanto, não pretendo fazer ninguém escrever código na prova

**Comment by alisonaran** [comment]
@iagoac , muito obrigado!

**Comment by c3kl** [comment]
A página da disciplina onde a prova será colocada é qual? A deste repositório mesmo? No README.md ou em outro lugar?

**Comment by iagoac** [comment]
https://github.com/iagoac/mc202/tree/master/exame_final

**Comment by c3kl** [comment]
Últimas duas perguntas... Pode enviar o email como um só PDF? E, só para confirmar, devemos enviar ao email colocado no seu perfil aqui do git?

**Comment by iagoac** [comment]
Sim, o e-mail aqui do git: iagoac@ic.unicamp.br

Sim, você também pode enviar como um único PDF

**Comment by iagoac** [comment]
As provas já estão disponíveis online. Se atentem para o dígito final de seu RA

**Comment by alisonaran** [comment]
@iagoac , boa noite! Terminei a prova e enviei o e-mail com as fotos.
Só estou escrevendo aqui para registrar rsrs.
Obrigado!

**Comment by GustavoThomaz** [comment]
Professor, tem problema se enviar a resolução em um pdf com as fotos em ordem ?

**Comment by iagoac** [comment]
@GustavoThomaz nenhum problema. Discutimos isto aqui em cima hoje cedo

**Comment by iagoac** [comment]
Fim do prazo para recebimento das provas
