### ISSUE TITLE
Problema de ordenação

### ISSUE THREAD

**Issue by MacavityBrazil** [iagoac/mc202#145]
![Sem título](https://user-images.githubusercontent.com/67623581/91000141-e226ab80-e59e-11ea-9fc4-76f9e5ac9d30.png)

Não consegui achar uma definição fácil de 4 bits menos significativos na base 10, mas eu assumi que é o ultimo algarismo. Eu não não consigo achar um algoritmo que seja capaz de tal feito. Eu pensei em separar em blocos onde cada bloco são todos os números que tem todos os algarismos, exceto o ultimo, iguais mas mesmo assim...

**Comment by iagoac** [comment]
Os 4 bits menos significativos são os quatro bits a direita, em uma representação binária. Então, você pode assumir que os números variaram, no máximo, um valor de 15 (para mais ou para menos). 

Como o exercício diz que os números são extremamente grandes (com muitos dígitos), você pode fazer somente pequenas alterações na ordenação atual.  
Faça um _loop_ iterando sobre todas as posições do vetor e comparando cada elemento com seus vizinhos, sempre fazendo trocas quando necessário. A complexidade deste algoritmo é _O(n)_.

Não é garantido que o novo vetor realmente esteja ordenado, mas existe uma grande probabilidade que isto ocorra.
