### ISSUE TITLE
notas finais

### ISSUE THREAD

**Issue by lucas-rsantos** [iagoac/mc202#146]
Professor, as notas ainda não foram computadas no sistema da DAC?pq para mim, a matéria ainda esta em aberto na integralização, mesmo não precisando fazer o exame

**Comment by iagoac** [comment]
@lucas-rsantos a matéria ainda está em aberto, pois vou postar as notas do exame final daqui a pouco.  
Já já eu fecho todas as turmas

**Comment by iagoac** [comment]
Notas lançadas!
