### ISSUE TITLE
Login e senha Susy

### ISSUE THREAD

**Issue by Vomartins** [iagoac/mc202#15]
Não lembro meu login e senha do Susy, última vez que usei foi em 2017, como posso recuperar esses dados?

**Comment by gabdelavald** [comment]
Estou com o mesmo problema

**Comment by iagoac** [comment]
@Vomartins estou verificando como é este processo.
Assim que tiver mais informações, eu respondo aqui

**Comment by carlosecb** [comment]
O login e senha são o RA e a senha da DAC. Não sei se ele atualiza junto com a senha da DAC ou não, mas deve ser a que estava no início do semestre.

**Comment by iagoac** [comment]
Bem, o login é realizado diretamente no servidor da DAC e não existe nenhuma senha específica do Susy. Como o @carlos-ecb falou, o login é seu RA e a senha é a mesma que você utiliza na DAC.

Caso você não saiba a sua senha da DAC, você pode solicitar outra no endereço [https://www.unicamp.br/senhaunicamp/](https://www.unicamp.br/senhaunicamp/)

**Comment by Vomartins** [comment]
Consegui fazer o login, obrigado a todos!
