### ISSUE TITLE
Tetes do laboratório 1

### ISSUE THREAD

**Issue by ghost** [iagoac/mc202#17]
Há algo de errado com os valores de saída (itens 3 e 4) do laboratório 1 no susy. Por exemplo,  teste 1 aberto:
5
95 21 93 86 96 
29 67 33 4 76 
47 34 77 45 82 
38 67 3 19 48 
9 48 1 96 70 

item 3:
95 + 21 + 93 + 86 + 96 = 391
29 + 67 + 33 + 4 + 76 = 209
47 + 34 + 77 + 45 + 82 = 285
38 + 67 + 3 + 19 + 48 = 175
9 + 48 + 1 + 96 + 70 = 224
Portanto, têm apenas 1 linha com soma par e não 3.

item 4:
95+29+47+38+9 = 218
21+67+34+67+48 = 237
93+33+77+3+1 = 207
86+4+45+19+96 = 250
96+76+82+48+70 = 372
Portanto, têm apenas 3 linhas com soma impar e não 4.

**Comment by enoque** [comment]
Bom dia!! No primeiro PDF lançado estava trocado onde era linha por coluna e vice-versa. 

O correto seria: 

> O seu código deve exibir na tela quatro inteiros separados por espaço, representando respectivamente: soma da diagonal principal, soma da diagonal secundária, quantidade de colunas com somatório de valor par e a quantidade linhas com somatório de valor impar.

**Comment by enoque** [comment]
Logo logo o PDF será atualizado.

**Comment by enoque** [comment]
PDF atualizado. Caso ainda esteja tendo problema, dá uma olhadinha lá agora.

**Comment by Luceedit** [comment]
Professor estou tendo problemas com as saídas do laboratório, quando submeto meu código no Susy ele retorna: 

Teste 01: resultado incorreto

    328 253 3 4						      /	328 253 3 4

Teste 02: resultado incorreto

    530 504 6 6						      /	530 504 6 6

Teste 03: resultado incorreto

    1085 1129 11 7						      /	1085 1129 11 7

Teste 04: resultado incorreto

    1591 1540 11 15						      /	1591 1540 11 15

Teste 05: resultado incorreto

    2047 2091 25 19						      /	2047 2091 25 19

Teste 06: resultado incorreto

    2523 2425 25 23						      /	2523 2425 25 23


Não estou conseguindo identificar o erro. Além disso, gostaria de saber quantas chances de submissões temos no Susy.

**Comment by enoque** [comment]
Boa noite!! Provavelmente você está colocando alguem espaço ou quebra de linha a mais na saida. Note que a saida deve ser "printf("%d %d %d %d", var1, var2, var3, var4);". 

Sobre a quantidade de chances, não lembro bem ao certo, mas acho que é 15. Mas creio que isso posso ser estendido, caso seja preciso.

**Comment by Luceedit** [comment]
O printf no meu código esta  " printf("%d %d %d %d",SomaP,SomaS,NLP,NLI); " , não consegui notar nenhuma diferença da forma descrita pelo senhor, poderia ser algum outro problema?

**Comment by enoque** [comment]
Se está assim então também não sei o que pode ser. Me manda teu código pelo e-mail enoquealvesufc@gmail.com pra eu dá uma olhada e ver o possível problema.

**Comment by Luceedit** [comment]
Boa noite professor, fiz algumas mudanças no meu código e submeti ele novamente no Susy. O erro apontado agora é :
 
Teste 01: erro de processamento 

    (código devolvido pela execução: 1)

Não consegui entender qual é o erro, e nem oque esta errado no meu código, pois quando faço os testes no meu computador não ocorre nenhum problema.

**Comment by enoque** [comment]
Desculpa a demora Luiz!! Te respondi por e-mail. Porém, respondendo aqui para que outros que possam tá com essa dúvida também saber, seu erro é que tu tá retornando 1 no fim do teu código. O "return 0" no fim do código serve justamente pra indicar que o código executou tudo ok e não teve nenhum erro; quando tu retorna algo que não é "0", o SO reconhece como se tivesse algum erro no código.

**Comment by enoque** [comment]
Testa colocando "return 0" no final e veja a mágica acontecer... :)
