### ISSUE TITLE
Disponibilização dos testes do SuSy

### ISSUE THREAD

**Issue by lucas-vecina** [iagoac/mc202#18]
Teria como nesse e nos próximos labs disponibilizar um único arquivo <.zip> contendo todos os testes abertos (<.in> e <.res>)? Facilitaria muito, especialmente para labs mais complexos, na hora de [testar antes de submeter para o Susy](http://blog.erikperillo.xyz/post/passando-o-teste-do-susy-no-seu-computador.html).

**Comment by enoque** [comment]
Se o @iagoac autorizar, posso fazer isso sem problemas.

**Comment by sentineladonorte** [comment]
Isso ajudaria muito

**Comment by iagoac** [comment]
@lucas-vecina @enoque com os testes abertos, sem problema.
Podemos organizar cada laboratório em uma pasta com os arquivos de entrada e saída
