### ISSUE TITLE
Dúvidas gerais e sobre o lab1

### ISSUE THREAD

**Issue by leo-kenji** [iagoac/mc202#19]
Eu tenho algumas dúvidas:
1) Eu deveria usar um Issue por dúvida?
2) Eu vi em outra resposta que a matriz de dimensão NxN já é satisfeita por um N=100, mas no caso se fosse necessário alocar de forma "dinamica" o array, eu poderia usar VLAs? (já que estamos usando c99 (apesar das questões da memória e de algumas pessoas não gostarem do uso de VLAs, e de não ser exatamente "standard")), ou eu deveria usar apenas o malloc?
3)Vocês irão olhar os códigos, ou eles serão apenas avaliados pelo Suzy?
4)No caso de vocês olharem ele, eu preciso comentá-lo?
5)Novamente caso vocês olhem, tem problema cometer "barbaridades" como utilizar variáveis globais?
6)O algoritmo deve esperar apenas input "bom", ou ele deve saber lidar com qualquer tipo de input?

**Comment by iagoac** [comment]
@leo-kenji 
1. sim, uma _issue_ por cada dúvida. Isto ajuda na organização do fórum de dúvidas e faz com que fique mais fácil outros alunos pesquisarem.
2. Eu realmente recomendo a utilização do malloc (ou calloc) em detrimento de VLAs. É muito incomum você utilizar VLA em algum código por não ser uma prática, como você mesmo disse, _standard_.
3. Depende do caso. Algumas vezes será necessário olhar o código para verificar a estrutura de dados que foi utililzada. Por exemplo, existe uma implementação por recursão e outra implementação por pilhas para um determinado problema. Caso esteja se tratando do laboratório de pilhas, então o aluno deverá literalmente implementar uma pilha. Neste caso, será necessário verificar o código.
4. Comentar o código é uma boa prática de programação. Recomendo que se faça isso em todos os laboratórios.
5. A utilização de variáveis globais não é uma boa prática de programação e não é recomendado sua utilização. Entretanto, ninguém vai perder ponto por causa disso.
6. Eu não pretendo dar um input _ruim_ em momento algum (a não ser que o enunciado do laboratório diga explicitamente isto)
