### ISSUE TITLE
Gostaria de compartilhar um ambiente pré-definido

### ISSUE THREAD

**Issue by emilioCosta** [iagoac/mc202#20]
Boa tarde, @iagoac . Gostaria de saber se teria como eu contribuir no repositório. Criei um tutorial para configuração de uma máquina virtual e como utilizar umas funções auxiliares para execução de testes de execução e varredura nos laboratórios.

Vou commitar em uma branch separada da master e abrir um Pull Request, dessa forma teria como pré-avaliar a nova feature.

Caso não seja possível autorizar meus commits, posso mandar a pasta de Ambiente por email para uma avaliação. Acho que seria útil.

**Comment by iagoac** [comment]
@emilioCosta 
pode fazer seu pull request que eu avalio posteriormente.
Se preferir, também pode me enviar os arquivos que eu mesmo os coloco aqui no repositório

**Comment by emilioCosta** [comment]
Beleza, abri o PR e fico no aguardo!
