### ISSUE TITLE
Entrega de Labs

### ISSUE THREAD

**Issue by Lublanski** [iagoac/mc202#22]
Professor, como vai ficar a entrega dos laboratórios? Vão ter data?

**Comment by iagoac** [comment]
@Lublanski sim, todos eles vão ter data.
Cada um vai ter um prazo mínimo de 7 dias (muito provavelmente, todos terão um prazo maior).
Mas, todos os labs terão um deadline.

Caso eles sejam entregues após este dealine, será descontado 25% da sua nota

**Comment by Lublanski** [comment]
prazo mínimo????
