### ISSUE TITLE
conceitual - chamando funcöes

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#24]
Vamos supor a seguinte expressäo:
"
1.  p_no criar_lista () {
2.  	return NULL;
3.  }
4.  p_no lista;
5.  lista = criar_lista ();
"
Por que a linha 4 näo implica a linha 5? Qual é a razäo de se colocar um nome antes de uma funcäo (linha 1)?

**Comment by enoque** [comment]
Se eu entendi bem, é pq lista não é um ponteiro e nem a função retorna um ponteiro. Coloca "*" na hora de declarar e testa ai.

**Comment by enoque** [comment]
O nome da função indica o que vai ser retornado. Por exemplo, "int f(){return 0;}" o int indica que a função retornará um inteiro. No seu exemplo, "p_no" provavelmente é uma struct e você tá indicando que a função retornará uma variável essa struct.

Não entendi a primeira pergunta.
