### ISSUE TITLE
Senha do Susy

### ISSUE THREAD

**Issue by Lublanski** [iagoac/mc202#25]
Professor, faz muito tempo que não logava no susy. Não lembro minha senha, felizmente ela esta salva, mas não da para ver qual é, ela só acessa. No caso de o cookie ser limpo,  qual o procedimento que devo tomar para recuperar essa senha???

**Comment by iagoac** [comment]
@Lublanski pergunta já respondida [aqui](https://github.com/iagoac/mc202/issues/15)
