### ISSUE TITLE
Dúvidas sobre struct

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#26]
Nas aulas, foi mostrada a seguinte struct:

typedef struct No {
        int dado;
	struct No *prox;		
} No;

typedef struct No * p_no;

Näo entendi completamente do porquê é necessário escrever outro typedef de struct No.
Qual seria a diferenca caso näo tivesse o 1° typedef?

**Comment by ianloron00** [comment]
Creio que entendi! É porque o segundo caso é um ponteiro, e No se diferencia de p_no por isso...
Só para ficar claro sobre os ponteiros, * vem antes do nome quando os declaramos ou quando chamamos em uma funcäo: *(nome). Quando escrevemos (nome)* ?

**Comment by silas96** [comment]
Isso, a segunda struct é um apontador para o tipo criado em cima.

Quanto à segunda pergunta, não entendi direito, mas o * é usado na declaração de um ponteiro como parte do tipo. Ex: int *, char *, double *, struct nome *. Todos esses são ponteiros para os respectivos tipos que eles seguem.

Não entendi direito a parte da função que perguntou, mas é possível usar o * também no corpo de uma função, geralmente para acessar a variável apontada pelo ponteiro (um pouco confuso, mas é isso mesmo). Ex _(considerando que pont_a seja um ponteiro para **a**. E **a** seja do tipo int)_ : *pont_a=2; seria uma forma de acessar **a** e alterar seu valor. Isso pode ser útil, por exemplo, para alterar o valor de uma variável da main em uma outra função. Queria entender melhor o que você quis dizer na segunda parte da pergunta pra não te confundir, se não fui claro só falar.

**Comment by ianloron00** [comment]
Ah, o github mudou a caligrafia hehe 
Tinha escrito [estrela] (nome) e (nome) [estrela]. Fiquei confuso quanto a posicao do * .
Tinha entendido que transformávamos No em um ponteiro, mas agora entendi que o ponteiro é p_no.

Obrigado

**Comment by iagoac** [comment]
Pessoal, quando forem postar código aqui, usem o _insert code_.
Ele faz a fonte ficar mono-espaçada e mais legível.

```typedef struct No {
int dado;
struct No *prox;
} No;

typedef struct No * p_no;
```

**Comment by iagoac** [comment]
> o ponteiro é p_no
exatamente isso. neste caso, `p_no` é um ponteiro para a struct `no`.

É um pouco confuso de começo, mas você acaba pegando o jeito com o passar do tempo.

**Comment by silas96** [comment]
> Ah, o github mudou a caligrafia hehe
> Tinha escrito [estrela] (nome) e (nome) [estrela]. Fiquei confuso quanto a posicao do * .
> Tinha entendido que transformávamos No em um ponteiro, mas agora entendi que o ponteiro é p_no.
> 
> Obrigado

Quando for assim testa no programa mano. Existe provavelmente um padrão pra escrever, e talvez seja isso que queira saber, mas às vezes funciona de mais de um jeito. no caso precisa ser `*nome` o contrário ele não entende. As limitações a gente vai descobrindo testando. Faço isso bastante. Dá mais trabalho, mas depois você consegue ter certeza e até usar em outras situações o que aprendeu. Mas ainda assim espero ter ajudado, ainda que não tenha respondido tudo.
