### ISSUE TITLE
Dúvida Lab 02

### ISSUE THREAD

**Issue by leo-leao** [iagoac/mc202#27]
Bom dia, tudo bem?
Com relação ao Lab 02, diz que X deve ser menor que Y, mas não é explicito o que deve acontecer caso Y seja maior que X. O que devo fazer nesse caso?

**Comment by leo-leao** [comment]
Outra dúvida é com relação a quantidade de submissões no Susy. Uma vez que eu não tenho linux em minha máquina para testar os códigos diretamente, a quantidade de submissões no Susy, havendo a última correta, influência na nota final?

**Comment by arthurlopes** [comment]
> Bom dia, tudo bem?
> Com relação ao Lab 02, diz que X deve ser menor que Y, mas não é explicito o que deve acontecer caso Y seja maior que X. O que devo fazer nesse caso?

Voces nao precisam se preocupar com esse caso, pois se Y for menor que X temos uma entrada invalida. Os intervalos fornecidos sempre serao validos.

**Comment by arthurlopes** [comment]
> Outra dúvida é com relação a quantidade de submissões no Susy. Uma vez que eu não tenho linux em minha máquina para testar os códigos diretamente, a quantidade de submissões no Susy, havendo a última correta, influência na nota final?

O importante é a ultima submissao estar correta, nao importa a quantidade de submissoes.

**Comment by leo-leao** [comment]
Muito obrigado Arthur, eu submeti o lab para o Susy, foi certinho. Entretanto usei alocação dinâmica apenas para armazenar os dados de entrada de entrada do usuário, já para o de saída deixei com um tamanho fixo. Você acha melhor eu deixar o de saída em alocação dinâmica também?

**Comment by enoque** [comment]
Me expressei de maneira bem ruim ai msm. O que quis dizer é que em toda entrada, X vai ser menor que Y. Como foi dito, a parte da entrada você não "mexe", você só recebe; a gente é que fornece para vocês.

Sobre as submissões do susy, existe um limite de 20 submissões na tarefa justamente para que não se fique usando o susy como compilador e vocês tenham a experiência da mesma.  Já que tá sem Linux, recomendo um compilador online.

**Comment by arthurlopes** [comment]
> Muito obrigado Arthur, eu submeti o lab para o Susy, foi certinho. Entretanto usei alocação dinâmica apenas para armazenar os dados de entrada de entrada do usuário, já para o de saída deixei com um tamanho fixo. Você acha melhor eu deixar o de saída em alocação dinâmica também?

Nao entendi muito bem a pergunta. O que seria o seu array de saida?

**Comment by leo-leao** [comment]
É que para armazenar os resultados da função de consulta de casos, uso um segundo array, visto que essas chamadas podem ser feitas antes da apresentação do resultado final. Ao depois de todo os processamento das entradas, percorre o array saida mostrando os resultados. Só que esse array eu não deixei como dinâmico, define um tamanho fixo para ele, ai gostaria de saber se ele também deveria alocação dinâmica.

**Comment by arthurlopes** [comment]
> É que para armazenar os resultados da função de consulta de casos, uso um segundo array, visto que essas chamadas podem ser feitas antes da apresentação do resultado final. Ao depois de todo os processamento das entradas, percorre o array saida mostrando os resultados. Só que esse array eu não deixei como dinâmico, define um tamanho fixo para ele, ai gostaria de saber se ele também deveria alocação dinâmica.

Acho que entendi, voce alocou um array com tamanho N (numero de linhas dado no comeco da entrada). Se for este o caso, voce nao precisa deste array, pois pode ir imprimindo os valores conforme for recebendo consultas.

**Comment by Luceedit** [comment]
Boa noite, estou com um problema com o Susy, quando eu faço os testes no meu computador eles dão certo, mas ao submeter no Susy todos os testes dão errado. Um exemplo disso é o teste 1, que no meu computador exibe o resultado "815" na ultima busca, mas no Susy exibe "660". 

Teste 01: resultado incorreto

    660							      |	815


Eu tentei rever se havia algum problema de lógica, mas não consigui encotrar. Gostaria de saber se eu poderia enviar meu código para algum dos PEDs.
