### ISSUE TITLE
Link Susy MC202 turma D

### ISSUE THREAD

**Issue by Eduardokls** [iagoac/mc202#28]
Por favor, alguëm pode me passar o link do Susy para a turma D de MC202. Só encontrei das turma A B C e acredito ser bem diferente dos labs dessa turma.

**Comment by arthurlopes** [comment]
link para as turmas D, E, F e G: https://susy.ic.unicamp.br:9999/mc202defg

**Comment by Eduardokls** [comment]
Obrigado.
