### ISSUE TITLE
Script test.sh

### ISSUE THREAD

**Issue by Eduardokls** [iagoac/mc202#29]
Aqui no repositório existe um arquivo contendo os testes abertos do Susy para serem usados com o script test.sh?
Tentei copiar do Susy e salvar o arquivo com a extensão .in e .res mas esta dando o erro:

>root@eduardo-VirtualBox:/home/eduardo/Documentos/MC202/lab1# ./test.sh lab1 tests
>
>--- begin of tests ---
>
>--- in tests/arq01.in --- INCORRECT
><<<< diff result: >>>>
>1c1
>< ./test.sh, linha 58: 19967 Falha de segmentação  (imagem do núcleo gravada) $cmd./"$program" >< $test_case
>---
>> 328 253 3 4
>\ Nenhum caractere de nova linha no final do arquivo
>
>--- end of tests ---
>
>correct results (0):
>	 
>incorrect results (1):
>	 arq01.in 
>

Quando eu digito uma matriz no arquivo funciona normalmente. Alguém sabe o que ocorre e pode me ajudar?
Ou tem os arquivos aqui no repositório para baixar e colocar na pasta <lab1/tests> dentro do diretório do projeto?

**Comment by Eduardokls** [comment]
Descobri o problema, eu estava alocando de maneira errada o espaço da matriz, ao alocar o espaço para um ponteiro eu usei sizeof(int) ou invés de sizeof(int*). Desta maneira o programa alocava um numero errado de bytes.

**Comment by iagoac** [comment]
@Eduardokls este arquivo não é disponibilizado aqui no git.
Entretanto, vou tentar disponibilizar os arquivos de entrada para o laboratório 2 e os subsequentes

**Comment by Eduardokls** [comment]
Se alguém precisar eu tenho disponíveis aqui os 6 testes abertos. (12 arquivos). Funcionou muito bem com o script test.sh.

**Comment by Eduardokls** [comment]
@iagoac muito obrigado, se conseguir disponibilizar agiliza bastante os testes.
