### ISSUE TITLE
Erro de Processamento

### ISSUE THREAD

**Issue by igorloss500** [iagoac/mc202#32]
Boa noite professor!

Fiz o LAB02 e rodei no terminal do meu computador como os testes do susy e passei em todos os eles. No entanto, quando fui submeter o código no susy, apareceu uma mensagem de erro logo abaixo de cada teste:
Exemplo:

"Teste 05: erro de processamento
                provavelmente memória corrompida (código 134)"

Poderia, por favor, me ajudar a solucionar esse problema?
Atenciosamente,
Igor

**Comment by igorloss500** [comment]
Alguem poderia me ajudar?

**Comment by johnvpc** [comment]
estou com o mesmo problema se alguem puder ajudar?

**Comment by iagoac** [comment]
Vou verificar o que está acontecendo.
Assimque eu souber de novidades, eu respondo aqui
@enoque vc consegue ajudar?

**Comment by Tomikins** [comment]
estou com o mesmo problema, alguns testes dão resultado correto, e outros dão erro de processamento, no meu caso o teste 8 deu resultado correto.

![image](https://user-images.githubusercontent.com/53408343/80783471-4fc24e00-8b50-11ea-990a-0f8d7f846732.png)

**Comment by iagoac** [comment]
@Tomikins @igorloss500 @johnvpc terminei de verificar tudo e o exercício está OK
Diversas pessoas já conseguiram submeter a tarefa com sucesso, sendo todos os testes aprovados

Por favor, confiram os códigos de vocês. Provavelmente ambos estão cometendo o mesmo erro

**Comment by Tomikins** [comment]
@iagoac não pode nos ajudar? meu código está no meu repositório como lab2.c
o que é curioso é que um teste funciona...

**Comment by Tomikins** [comment]
@igorloss500 @johnvpc , encontrei o erro.
Na hora de realocar, ou alocar, estamos zerando um endereço a mais no vetor, aí quando você tentar escrever um int, num lugar que estão alocados 0 bytes e corrompe a memória.
Pelo menos pra mim foi isso
