### ISSUE TITLE
Funções do lab 2

### ISSUE THREAD

**Issue by murilo-goncalves** [iagoac/mc202#33]
Bom dia! No lab 2 as funções adicionar e consultar precisam possuir **exatamente** dois parâmetros, X e Y, ou podem possuir mais?

**Comment by enoque** [comment]
Sim, possui **exatamente** dois parâmetros.

**Comment by murilo-goncalves** [comment]
não pode nem ter o ponteiro do vetor dinamico?

**Comment by murilo-goncalves** [comment]
pra fazer isso não teria que usar variável global?

**Comment by murilo-goncalves** [comment]
e outra, podemos usar um vetor de structs? ou necessariamente um vetor de ints?

**Comment by enoque** [comment]
Ahhh.

Acho que você entendeu errado. Quando falo dos parâmetros, me refiro a **ENTRADA** do programa, que é basicamente um _.txt_ contendo os valores para seu programa trabalhar. 

Já a sua função para realizar o que é pedido é outra coisa. Você pode criar uma função consultar(p1,p2,p3,...,pn) com o numero de parâmetros que achar necessário (e que faça sentido também).

Evite variável global (a ideia é não usar nenhuma).

**Comment by murilo-goncalves** [comment]
perfeito! Obrigado, e podemos usar um vetor de structs?

**Comment by iagoac** [comment]
Caso seja necessário, sinta-se a vontade para usar
