### ISSUE TITLE
duvida e monitoria

### ISSUE THREAD

**Issue by JonasRoberto** [iagoac/mc202#34]
oi estou com duvida no lab2 e preciso de ajuda, gostaria de saber se tem alguma monitoria. eu ja foi em uma mas a pessoa em questão não apareceu no dia.

**Comment by iagoac** [comment]
@JonasRoberto era para as monitorias estarem ocorrendo normalmente.
Que dia/horário você procurou os monitores?

**Comment by JonasRoberto** [comment]
foi uns dias antes de lançar o lab1, eu estava com duvida na teoria e nao encontrei ninguem na monitoria do dia

**Comment by iagoac** [comment]
Teve um dia que um dos monitores ficou sem internet em sua casa e não conseguiu dar a monitoria. Provavelmente foi nesta mesma data... No geral, elas tem ocorrido normalmente
