### ISSUE TITLE
condicional do lab2: X < Y

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#37]
Bom dia,
É uma dúvida bem simples, mas que nao ficou claro no enunciado. Se X !< Y, é pra fazer o que?
Ignorar os valores mas contar uma iteracao, iterar de novo... ?

**Comment by iagoac** [comment]
@ianloron00 por !<, você quis dizer não menor?
Você pode assumir que _X_ é sempre menor que _Y_, como dito nas _Observações de entrada_
