### ISSUE TITLE
Dúvida sobre o erro "Realloc () invalid next size"

### ISSUE THREAD

**Issue by pedro-ferraz** [iagoac/mc202#38]
Boa noite! Estou com uma dúvida em relação à função realloc em meu código (linha 24
 abaixo) na qual ele aloca o dobro da memória anterior, caso seja necessário. Meu código está funcionando corretamente até um limite máximo de 14 linhas de dados de entrada (portanto 42 elementos no vetor). Caso o usuário digite mais uma linha, o programa para durante o scanf e retorna o erro "Realloc () invalid next size".
Alguém poderia me auxiliar, por favor?
Obs: Caso eu defina o realloc para o triplo de memória anterior, não ocorre mais esse problema, mesmo com os últimos testes do susy.
Obrigado!
![Captura de tela de 2020-05-02 17-48-41](https://user-images.githubusercontent.com/63692033/80891899-64f8c300-8c9d-11ea-82a1-ca7a5bbe1f96.png)
Obs 2: i inicia com valor 0 e j inicia com valor 4.

**Comment by Tomikins** [comment]
Creio que tenha a ver com a ordem das operações pra calcular o espaço
alocado, deve estar alocando um espaço que não é múltiplo de 4. Por
exemplo, ali se i =1, o resultado da operação é 21. Coloque alguns
parênteses pra ordenar as operações e deve dar tudo certo

**Comment by iagoac** [comment]
@pedro-ferraz acredito que a sugestão de @Tomikins faça sentido.
Este erro que você reportou acontece muito quando você está realocando um espaço de memória inferior ao espaço de memória já reservado anteriormente para o vetor.

Organize sua expressão com mais cuidado que provavelmente vai dar certo :)
