### ISSUE TITLE
[lab2] Alocação duplica capacidade de memória anterior

### ISSUE THREAD

**Issue by alimarques** [iagoac/mc202#39]
Bom dia, uma dúvida quanto ao enunciado do lab 2.

Nas restrições, fala que a memória realocada deve duplicar a capacidade de memória anterior, mas não podemos só realocar a quantidade necessária de memória, de acordo com a idade da operação?

**Comment by ghost** [comment]
Não é uma boa idéia... Realocação de memória é uma operação custosa, então o certo é realocar o dobro da memória anterior sempre
