### ISSUE TITLE
Dúvida Sobre a Entrega dos Laboratórios

### ISSUE THREAD

**Issue by RPanosso** [iagoac/mc202#40]
@iagoac gostaria de saber se algum laboratório for entregue após a data limite se ainda vai ter aquele lance de ele valer no máximo 7, porém ainda poder entregar

**Comment by iagoac** [comment]
@RPanosso no final do semestre eu vou abrir todos os labs para entrega novamente.
Eles vão valer 75% da nota original

**Comment by silas96** [comment]
Professor, já existe uma prévia de quando serão abertos todos os labs atrasados pra submissão??

**Comment by iagoac** [comment]
@silas96 acredito que todos eles já estejam abertos.  
Por favor, dê uma olhada no Susy.

Caso algum laboratório atrasado ainda não esteja aberto, envie uma nova mensagem aqui neste fórum mencionando meu usuário que eu resolvo rapidamente a questão.

**Comment by silas96** [comment]
Sim, estão sim, perguntei antes de olhar...

Valeu Professor.
