### ISSUE TITLE
erro nos teste 3,4,5,6,7

### ISSUE THREAD

**Issue by luizsimioni** [iagoac/mc202#41]
Está dando este erro no teste 3 quando rodo no meu computador mais quando tentei no susy está correto:
 free(): double free detected in tcache 2 Aborted make: *** [Makefile:30: testar_programa] Error 134
No meu código tem a função free() depois de todo o procedimento, tenho que coloca-la durante o procedimento ou pode ser apenas no final mesmo?
Nos testes 4,6,7 apenas alguns valores estão dando errado no susy,
No teste 5 quando rodei no susy está dando erro de processamento 
provavelmente memória corrompida (código 134).
Alguma ideia do problema no meu código?
Estou usando a função Realloc, tem algum problema?

**Comment by iagoac** [comment]
@LuizluHenrique 
> free(): double free detected in tcache  

isso acontece quando vc dá `free()` em uma variável (vetor, matriz) que já foi desalocada previamente.

> tenho que coloca-la durante o procedimento ou pode ser apenas no final mesmo?
  
não faz sentido você colocar o `free()` no final do seu código, pois, assim que o programa é terminado, todo o espaço de memória reservado por ele é liberado automaticamente pelo sistema operacional. No meu ponto de vista, isso só gera erros.

> No teste 5 quando rodei no susy está dando erro de processamento provavelmente memória corrompida (código 134).  

Diversas pessoas estão tendo/tiveram este mesmo problema. Já ouve uma pequena discussão sobre este erro [aqui](https://github.com/iagoac/mc202/issues/32). Veja se isto consegue te ajudar.

> Estou usando a função realloc, tem algum problema?

Nenhum problema. Aliás, o ideal realmente é a utilização do `realloc`

**Comment by luizsimioni** [comment]
Mais mesmo quando eu não utilizo free() em nem um lugar ele esta aparecendo este erro.

**Comment by Tomikins** [comment]
A função realloc usa o free() no código dela, seu erro deve estar nos
parametros dela, ou na hora de zerar seu vetor realocado.

**Comment by iagoac** [comment]
Sim, também acredito que o erro está nos parâmetros da função.
Dê uma olhada em como ela funciona na [documentação da linguagem](http://www.cplusplus.com/reference/cstdlib/realloc/)

**Comment by luizsimioni** [comment]
Todos os testes estão dando certo mais quando estou submetendo ao susy esta toda hora dando algum tipo de problema. As vezes fala que a resposta esta errada em alguns testes mais quando testo no meu computador a resposta sai tudo correto. E as vezes continua dando o erro de processamento provavelmente memória corrompida (código 134). Mas não acredito que esteja zerando parte do ponteiro que não existe. já testei de varias formas os meus While para zerar o vetor, com <,<= e sempre da esses erros. Teve uma vez que submeti e deu apenas o erro (134). Não sei mais o que fazer

**Comment by luizsimioni** [comment]
Pior que não consigo testar porque sempre da correto. Apenas consigo testar submetendo ao susy. Mais ja submeti mais de 10 vezes, estou com medo de passar dos 20

**Comment by luizsimioni** [comment]
Consegui professor, muito obrigado. Acho que estava faltando o (int*) nas funções realloc.

**Comment by iagoac** [comment]
@LuizluHenrique fico feliz que tenha dado certo.

Esta foi a única modificação necessária? Eu havia proposto essa modificação para diversos outros alunos aqui no git e alguns deles disseram que não foi o suficiente
