### ISSUE TITLE
Liberar memória alocada

### ISSUE THREAD

**Issue by Eduardokls** [iagoac/mc202#42]
Eu já submeti o código ao  Susy e todos os testes deram corretos, porém eu esqueci de liberar o espaćo de memória alocado usando o comando free() ao final do programa.
Devo submeter novamente com essa modificação ou é desnecessário?

**Comment by iagoac** [comment]
@Eduardokls 

acabamos de discutir isso [aqui](https://github.com/iagoac/mc202/issues/41)

Não faz sentido você colocar o `free()` no final do seu código, pois, assim que o programa é terminado, todo o espaço de memória reservado por ele é liberado automaticamente pelo sistema operacional. No meu ponto de vista, isso só gera erros. Deixe como está

**Comment by Eduardokls** [comment]
@iagoac 

Muito obrigado.
