### ISSUE TITLE
Nota do Susy

### ISSUE THREAD

**Issue by RPanosso** [iagoac/mc202#44]
@iagoac como funciona a nota do susy? A cada submissão feita diminui a nota, ou a nota é baseada só na ultima submissão e dessa forma se tem testes errados isso que tiraria a nota

**Comment by iagoac** [comment]
Você pode realizar a submissão diversas vezes, mas somente a última submissão contará para termos de avaliação.

Em geral, assuma que a nota é binária (ou passa em todos os testes ou não).
O enunciado do exercício irá dizer quando a nota binária não for aplicada.
