### ISSUE TITLE
Entregas com atraso no Susy

### ISSUE THREAD

**Issue by victorpmacc** [iagoac/mc202#45]
Boa noite! Após horas tentando resolver diversos erros no meu código do LAB2, fiquei com uma dúvida referente a entrega dos LABs pelo sistema Susy. Como funciona o desconto de nota para laboratórios entregues com atraso? Ainda há como entregar? O desconto é total, automático?

Agradecido!

**Comment by ghost** [comment]
Essa pergunta já foi respondida em outro issue. 
https://github.com/iagoac/mc202/issues/40
