### ISSUE TITLE
Apenas um arquivo para submissão

### ISSUE THREAD

**Issue by emilioCosta** [iagoac/mc202#46]
Professor, existe algum motivo para fazer tanto as estruturas, quanto o programa principal dentro de um mesmo arquivo? Teria alguma forma de extrairmos, um nó de uma lista, para um *.h e *.c separados, para melhor organização de responsabilidades e de leitura do programa?

**Comment by iagoac** [comment]
@emilioCosta eu não tenho certeza se é possível submeter mais de um arquivo no Susy.
Alguém aqui conseguiria responder esta pergunta?

**Comment by arthurlopes** [comment]
É possivel sim, ja tive varias materias com multiplos arquivos na submissao.

**Comment by arthurlopes** [comment]
Mas quem coloca a tarefa no susy é quem configura isso

**Comment by iagoac** [comment]
@arthurlopes obrigado. 
Vou procurar no manual do Susy como fazer esta configuração

**Comment by iagoac** [comment]
@emilioCosta pronto! Liberei a submissão de até 5 arquivos. Acredito que isto seja o bastante para a organização da tarefa
