### ISSUE TITLE
Exemplos de entrada e saída do lab3

### ISSUE THREAD

**Issue by Eduardokls** [iagoac/mc202#49]
# Exemplos entrada e saída

![Anotação 2020-05-04 144753](https://user-images.githubusercontent.com/62317028/80996582-6bf71100-8e16-11ea-9649-41793565c0f3.jpg)

Esta ultima linha na saída não deveria ser `0 4` ao invés de `4 0`?

**Comment by enoque** [comment]
Boa tarde!! Não deveria não, o exemplo está correto.


Na ultima interação só sobra 0 e 4, sendo que o primeiro atendente atendeu o 3 por ultimo... Ai o "movimento feito" é: 3 -> 4 -> 0 -> 4.

Já o movimento do segundo é: 1 -> 0 -> 4 -> 0.

**Comment by Eduardokls** [comment]
Boa tarde, entendi a lógica, obrigado pela explicação.
Eu estava entendendo errado, ao excluir os atendidos não são mais contados, estava errando aí.
