### ISSUE TITLE
Saídas do Lab 3

### ISSUE THREAD

**Issue by carlosecb** [iagoac/mc202#51]
Estou tendo problemas com as entradas e saídas do lab 3. O meu programa funciona corretamente de acordo com os exemplos do enunciado, mas não é aceito no susy e as saids são distintas em todos os testes
![Captura de tela_2020-05-04_21-16-06](https://user-images.githubusercontent.com/45350809/81025434-083c0a80-8e4d-11ea-874e-890105bc0c60.png)

**Comment by iagoac** [comment]
@carlos-ecb alguns alunos já conseguiram submeter o laboratório 03, tendo obtido resultados positivos em todos os testes. Desta forma, acredito que os resultados que estão no Susy estão corretos.

Assim, só me resta dizer que seu código ainda contém algum erro :(
Os exemplos apresentados na descrição do laboratório são pequenos. Muitas vezes, estes pequenos exemplos não conseguem capturar características especiais do problema que podem aparecer em instâncias maiores (como os casos de teste que estão no Susy).

É por este mesmo motivo que temos casos de teste fechados (haviamos esquecido de colocar no lab 02, mas eles estão de volta agora): seu código deve ser capaz de lidar com todas as condições especiais do problema (como a situação onde ambos os atendentes chamam o mesmo cliente, por exemplo).

**Comment by carlosecb** [comment]
O formato da correção do susy mudou? Porque tive a impressão de que a saida do lab era a entrada, como na imagem

**Comment by iagoac** [comment]
Nós mudamos agora e estamos testando um novo formato.
Como diversos alunos pediram anteriormente, agora é possível encontrar todos os arquivos de entrada e saída [aqui](https://susy.ic.unicamp.br:9999/mc202defg/03/dados/testes.html).

Desta forma, pode ser que o formato de saída do Susy tenha se alterado
