### ISSUE TITLE
(Lab03) Lista orfã

### ISSUE THREAD

**Issue by leo-kenji** [iagoac/mc202#52]
No meu algorítimo, fiz a implementação de tal forma que inicialmente eu tenho uma variável apontando para lista (semelhante aos slides), mas mais para frente no código, eu abandono essa variável (deixo de usá-la, e dou o valor de NULL a ela), e passo a usar duas outras variáveis para rodar a lista.
Há algum problema com esse método, ou eu devo implementar que nem um tipo padrão, onde o ponto de acesso é um endereço constante (tipo um array)?

**Comment by iagoac** [comment]
@leo-kenji é muito estranho que você retire uma variável de uma estrutura de dados desta forma. Em um projeto de software onde o desenvolvimento ocorre em equipe, tal ação pode levar a bugs inesperados (e quase que irrastreáveis) no projeto.

Entretanto, caso você esteja ciente disto e entenda perfeitamente o que está acontecendo, além dos motivos que o levaram a fazer tal mudança, eu já fico feliz. Você não sofrerá nenhuma penalização (no contexto desta disciplina) quanto a esta mudança.
