### ISSUE TITLE
Erro make preparar_ambiente

### ISSUE THREAD

**Issue by frangupe** [iagoac/mc202#53]
Nos últimos dois labs (03 e 04), o comando make preparar_ambiente está baixando o pdf do lab 01 e não do lab correspondente.

**Comment by iagoac** [comment]
@GFranciscoP por favor, dê mais detalhes.
De onde você está rodando este makefile?

**Comment by frangupe** [comment]
@iagoac Na pasta MC202. 
Após utilizar o makefile, dentro da pasta criada o arquivo pdf possui o nome correto (e.g lab_04.pdf), no entando o conteúdo desse PDF é o lab_01.pdf.
Isso aconteceu para o lab03 e para o lab04.

**Comment by iagoac** [comment]
Tem que atualizar as seguintes linhas do makefile
![image](https://user-images.githubusercontent.com/8388583/81357282-9e6c6c80-90a9-11ea-8105-fb97a8e8382d.png)

@emilioCosta você tem alguma sugestão para arrumar o arquivo?

**Comment by emilioCosta** [comment]
Tem um lugar onde passa os comandos.
`make preparar_ambiente LAB=03 PDF=3 MAX_TST=9`
Sendo que o MAX_TST, precisa olhar aqui: https://susy.ic.unicamp.br:9999/mc202defg/03/dados/testes.html
até qual teste aberto ele vai
