### ISSUE TITLE
deletar nó de lista circular duplamente encadeada.

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#55]
Estou com dúvidas a respeito de como deletar um nó específico em uma lista circular duplamente encadeada.
  Apesar de entender o conceito, o uso correto dos ponteiros nao está completamente claro para mim. Enfrentei alguns problemas. Gostaria de deixar como sugestäo aulas complementares.

Voltando para o exercício. Para testá-lo, fiz o seguinte código para deletar um nó, com o auxilio de "temp": 

```
/* havia mais código aqui em cima, para inserir os valores e definir as variaveis etc.*/
/* a parte de insercao de dados estava funcionando muito bem. 
   Meu problema está sendo com apagar. */

while (head != head->next)
{
		for (i = 1; i <= k; i++)
			head = head->next;
		temp = head->next;
		printf("%d ",temp->data);
		head->next = head->next->next; 
		free(temp);
		printf("temp->data deletado: %d\n",temp->data);
}
```

Esperava encontrar um erro no segundo printf. Porém, para minha surpresa, printava o mesmo valor do "temp->dado" anterior.  O valor nao era apagado.

Minha referencia é: 

```
struct node  
{  
    struct node *prev;  
    struct node *next;  
    int data;  
};  
typedef struct node* node;
```

 

Entre outras dúvidas, gostaria de saber se quando um ponteiro auxiliar aponta para um nó da lista, a memória de endereco do ponteiro auxiliar é transferida de lugar ou é o valor que está no endereco que é salva na memoria de endereco do ponteiro auxiliar? Ou ainda, a memoria do ponteiro auxiliar guarda simplesmente o endereco da outra memoria? 
O que acontece com as memorias quando voce der um free(ponteiro_auxiliar)?

Também queria entender melhor o que significa dois ponteiros simultaneos, por exemplo:
```lista->prox->prev = lista->prev;```

Grato desde já

**Comment by iagoac** [comment]
@ianloron00 pra essa eu vou ter que desenhar   :)

Vamos supor uma lista circular duplamente encadeada como abaixo, com 8 elementos. Pra facilitar, vamos supor que o primeiro elemento contenha o número 1, o segundo elemento o número 2, e assim por diante. A cabeça da lista (_head_) é o vértice que contém o elemento _1_. Neste caso, `k = 8`.

![image](https://user-images.githubusercontent.com/8388583/81459748-cfb36e00-9177-11ea-9749-f9a2616476bd.png)

Quando você faz

```
for (i = 1; i <= k; i++) {
    head = head->next;
}
```
você está dando uma volta inteira na lista e o _HEAD_ não sai do lugar.  Então `temp = head->next`, nós temos que `temp` aponta para o vértice _2_. 

Após `head->next = head->next->next;` e `free(temp)`, temos o seguinte. 

![image](https://user-images.githubusercontent.com/8388583/81460771-dba22e80-917d-11ea-8f3e-3fc65311ea34.png)


Note que agora `temp` aponta para exatamente o mesmo endereço de memória onde anteriormente existia o valor _2_. A memória foi desalocada com o comando `free()`.  
Entretanto, este comando não apaga o dado existente naquele espaço de memória. Na prática, ele só informa ao sistema operacional que este pedaço de memória está livre .  
Desta forma, quando você logo em seguida manda imprimir o espaço de memória, o dado antigo ainda está lá e é por isso que você vê o mesmo valor.

---

> Também queria entender melhor o que significa dois ponteiros simultaneos, por exemplo:
`lista->prox->prev = lista->prev´;

Para entender isso, vamos usar como exemplo a imagem acima (essa onde o vértice contendo o valor _2_ foi deletado) e suponha que `temp = lista`.  
A instrução `lista->prox->prev = lista->prev;` serve para você indicar o ponteiro `prev` o lugar exato onde ele tem que apontar. Note que no exemplo acima, o `prev` do vértice com o valor _3_ está indicando para o vértice que continha o valor _2_ que já foi desalocado. Desta forma, caso você tente acessar o `prev` do vértice _3_, seu programa indicará uma falha de segmentação (_segmentation fault_).  
O que `lista->prox->prev = lista->prev;` faz é dizer para o `prev` de _3_ apontar para _1_ ao invés de _2_.  
Esta é um pouquinho confusa, mas acredito que dê para entender pelo desenho.

---

> Quando um ponteiro auxiliar aponta para um nó da lista, a memória de endereco do ponteiro auxiliar é transferida de lugar ou é o valor que está no endereco que é salva na memoria de endereco do ponteiro auxiliar?

O ponteiro é exatamente isto: um ponteiro. Ele só indica um endereço de memória no computador. Quando você acessa um ponteiro, o que você está acessando na verdade é o endereço de memória para o qual ele aponta. Então, pode-se dizer que você acessa _o valor que está no endereco_.
