### ISSUE TITLE
(lab04) itoa é compatível? 

### ISSUE THREAD

**Issue by leo-kenji** [iagoac/mc202#56]
Pelo que eu entendi o pdf do lab dá como sugestão a utilização das funções: itoa e atoi. E até onde eu sei elas não são standard do c, como nós enviamos o código fonte para o Suzy ele seria capaz de compilar um código que usa essa função? (estou assumindo que o Suzy usa o gcc) (o libc/glibc padrão do gcc não tem essas funções, eu acho)

**Comment by arthurlopes** [comment]
Faz parte da stdlib, logo nao tem problema (http://www.cplusplus.com/reference/cstdlib/atoi/). Basta colocar `#include <stdlib.h>` no comeco do codigo.

**Comment by leo-kenji** [comment]
@arthurlopes De fato eu me enganei quanto ao `atoi`, mas parece que o `itoa` de fato não faz parte do padrão ANSI-C:
(http://www.cplusplus.com/reference/cstdlib/itoa/) seção: portabilidade.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=9149


> Faz parte da stdlib, logo nao tem problema (http://www.cplusplus.com/reference/cstdlib/atoi/). Basta colocar `#include <stdlib.h>` no comeco do codigo.

Eu postei isso, pois mesmo inserindo `#include <stdlib.h>` o meu compilador estava apontando um aviso que abortava a compilação.

**Comment by arthurlopes** [comment]
Realmente, só a `atoi` esta na stdlib.h. Nesse caso, uma solução seria implementa-la ou usar a alternativa recomendada no link que voce mandou. O que não é recomendado é o uso de outras bilbliotecas que nao sejam padrao, pois nao vai funcionar no susy.

**Comment by iagoac** [comment]
@leo-kenji você pode fazer o teste para nós e submeter um código no susy com estas duas funções para saber se compila?

> estou assumindo que o Suzy usa o gcc

Sim, ele usa gcc

**Comment by carlosecb** [comment]
Caso uma das funções não possa ser usada, uma ferramenta possível pra essa conversão é a função sscanf

**Comment by iagoac** [comment]
Note que a entrada é um número até 10²². Desta forma, você tem que ler ele diretamente como string, pois não existe nenhum tipo numérico no C que suporte este tamanho de entrada

**Comment by leo-kenji** [comment]
> @leo-kenji você pode fazer o teste para nós e submeter um código no susy com estas duas funções para saber se compila?


@iagoac Fiz o teste, o Suzy não compilou, aqui está a mensagem que ele mostra:
`
 Fase de compilação:

    Problemas na execução desta fase:

    lab4.c: In function ‘main’:
    lab4.c:13:5: warning: implicit declaration of function ‘itoa’ [-Wimplicit-function-declaration]
         itoa(i, buffer, 10);
         ^
    /tmp/ccXibkWE.o: In function `main':
    lab4.c:(.text+0x26): undefined reference to `itoa'
    collect2: error: ld returned 1 exit status
`


> Note que a entrada é um número até 10²². Desta forma, você tem que ler ele diretamente como string, pois não existe nenhum tipo numérico no C que suporte este tamanho de entrada

Sim, obrigado, depois de analisar o código eu percebi isso, estou levando em conta este fato

**Comment by iagoac** [comment]
@leo-kenji seu código inclua as seguintes bibliotecas?
```
#include <stdlib.h>
#include <string.h>
```

**Comment by iagoac** [comment]
> Caso uma das funções não possa ser usada, uma ferramenta possível pra essa conversão é a função sscanf

Sim, existem alternativas utilizando `sscanf` e `sprintf`

**Comment by leo-kenji** [comment]
> @leo-kenji seu código inclua as seguintes bibliotecas?
> 
> ```
> #include <stdlib.h>
> #include <string.h>
> ```

@iagoac Sim, aqui está o código que eu submeti:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

//Apenas um teste para ver se o suzy tem as funções itoa e atoi no seu libC

int main()
{
    int i = 10;

    char buffer[23];
    itoa(i, buffer, 10);
    printf("resultado da funcao itoa: %s\n", buffer);

    int teste = atoi("123");
    printf("resultado da funcao atoi: %d\n", teste);

    return 0;
}
```
Estou ciente de que a `math.h` não era necessária, apenas esqueci de removê-la

**Comment by iagoac** [comment]
Então deu ruim mesmo pra `itoa`.  
Bem, ela realmente não é necessária para a realização deste laboratório, pois a entrada é uma string e, caso vocês façam um bom gerenciamento das variáveis, só será necessário converter `char` para `int`.
