### ISSUE TITLE
[lab 3] Problema com memória corrompida e valores incorretos

### ISSUE THREAD

**Issue by ErikGoto** [iagoac/mc202#59]
Olá boa tarde,

Ao submeter meu lab 3 no susy alguns testes aparecem como _Erro de Processamento - provavelmente memória corrompida (código 134)_, enquanto outros testes divergem dos resultados esperados.

Em relação ao primeiro problema li que algumas pessoas tiverem o mesmo problema no lab 2. Tentei colocar um **if** para evitar que um mesmo endereço seja limpo duas vezes com o comando **free**, mas não deu certo.
Já em relação à divergência dos resultados não consegui achar nada que possa estar causando isso. Pois nos primeiros resultados tanto o susy como meu programa retornam os mesmos valores.

Estou usando uma lista circular duplamente encadeada, aqui estão as funções responsáveis por definir quais clientes serão atendidos, e após o antedimento eles são excluídos da lista.

`void remove_cliente(p_no atendente){
    if(!atendente) return;
   
    atendente->ant->prox = atendente->prox;
    atendente->prox->ant = atendente->ant;

    free(atendente);
    return;
}

void atendimento(p_no lista, int c, int k, int l){
    p_no atendente1 = lista->ant;
    p_no atendente2 = lista->ant;

    //---------------------------------------------------------------------  
    //1 atendente
    for (int i = 0; i<=c; i++){
        //Leva o atendente 1 até o cliente cabeça
        atendente1 = atendente1->prox;
    }
    
    //2 atendente
    for (int i = 0; i<=c; i++){
        ////Leva o atendente 2 até o cliente cabeça
        atendente2 = atendente2->prox;
    }

    //---------------------------------------------------------------------  
   
    p_no prox = atendente1;
    p_no ant = atendente2;

    do
    {
        atendente1 = prox;
        atendente2 = ant; 
        //Atendimento 1
        //printf("\nAtendente1: ");
        for (int i = 0; i<k; i++){
        atendente1 = atendente1->prox;  
        }
        printf("%d ", atendente1->dado); 
        //Atendimento 2
        //printf("Atendente2: ");
        for (int i = 0; i<l; i++){       
            atendente2 = atendente2->ant;
        }
        printf("%d\n", atendente2->dado);

        prox = atendente1->ant;
        ant = atendente2->prox;

        remove_cliente(atendente1);
        //Se os atendentes chamarem o mesmo cliente ele é excluído uma única vez
        if (atendente1->dado != atendente2->dado){
            remove_cliente(atendente2);
        }
        
    } while (atendente1->prox != atendente1);

 

}`

**Comment by carlosecb** [comment]
O uso do programa valgrind ajuda com problemas relacionados a memória

**Comment by nuncaseiescolher** [comment]
Sobre os valroes incorretos, da uma olhada nesse seus apontadores prox e ant, veja se vc nao ta excluindo algum nó pra onde eles apontam. Sobre a memoria, verifica se vc nao esta acessando memoria que ja foi liberada.

**Comment by iagoac** [comment]
```
atendente->ant->prox = atendente->prox;
atendente->prox->ant = atendente->ant;

free(atendente);
```

Isso aqui pra mim parece estar OK. Não acredito que seja a fonte do seu erro

---

> Já em relação à divergência dos resultados não consegui achar nada que possa estar causando isso. Pois nos primeiros resultados tanto o susy como meu programa retornam os mesmos valores.

Funcionar pra um caso específico não quer dizer que vá funcionar para todos. É por este exato motivo que temos diversos casos de teste. Você ainda está deixando passar alguma coisa

---

Porquê estes loops

```
//1 atendente
for (int i = 0; i<=c; i++){
    //Leva o atendente 1 até o cliente cabeça
    atendente1 = atendente1->prox;
}

//2 atendente
for (int i = 0; i<=c; i++){
    ////Leva o atendente 2 até o cliente cabeça
    atendente2 = atendente2->prox;
}
```
você faz `<=` e os outros você faz só menor?  
Dê uma conferida nisto. Pode ser que a fonte de seu erro esteja aí.

**Comment by iagoac** [comment]
Seu erro está no momento que faz a remoção.  
Quando você faz
```
prox = atendente1->ant;
ant = atendente2->prox;

remove_cliente(atendente1);
```
caso `ant == atendente1`, deu ruim pra você.  
De forma similar, caso `prox == atendente2` e você exclui o atendente2, também dá erro.

Você tem que fazer 
```
prox = atendente1->ant;
ant = atendente2->prox;
```
de forma mais inteligente.

**Comment by ErikGoto** [comment]
> você faz <= e os outros você faz só menor?

É porque nesse loop eu levo o ponteiro atendente até o "cliente cabeça" enquanto os outros preciso apenas pular **k** ou **l** vezes. Cheguei nesses resultados empiricamente.

> caso ant == atendente1, deu ruim pra você.
> De forma similar, caso prox == atendente2 e você exclui o atendente2, também dá erro.

Revisei meu Código e o problema realmente estava na maneira como eu definia um cliente/referência para os próximos passos, bastou um **if** para consertar.
Muito obrigado pela ajuda!
