### ISSUE TITLE
bug Makefile

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#6]
tanto pelo makefile quanto pelo metodo manual de se gerar um arquivo "cliente", depois de já ter "bla.o", obtive o seguinte erro:
 "
gcc cliente.o complexo.o -lm -o cliente
cliente.o: In function `main':
cliente.c:(.text+0x8a): undefined reference to `complexo_imprime'
cliente.c:(.text+0xa1): undefined reference to `complexo_absoluto'
collect2: error: ld returned 1 exit status
Makefile:4: recipe for target 'cliente' failed
make: *** [cliente] Error 1
"
creio que o arquivo näo está reconhecendo a pasta "complexo.h", visto que as funcoes que dao problemas sao desssa pasta.
O que posso fazer?

Atte,

**Comment by MatteusStranger** [comment]
Boa tarde,
Esse problema é de algum exercício especificamente? Não encontrei com essa descrição nos slides das aulas.
De qualquer forma, você relata que não consegue encontrar sua biblioteca e, por consequência, as suas funções. Experimenta colocar a sua biblioteca na mesma pasta que o seu código-fonte e referencie ele no início. Exemplo:

> ~/folder/
cliente.c complexo.h

No arquivo cliente.c inicie assim:

`#include<stdio.h>` 
`#include "complexo.h"`
...

Teste isso e depois relate se deu certo ou não.

**Comment by ianloron00** [comment]
Oi @MatteusStranger está na aula 05 - parte 4.
É pedido um exercício de se fazer essa biblioteca. Como näo deu certo, resolvi copiar os códigos do professor e segui o procedimento do power point dessa aula. Acabou dando nesse erro que enviei - conferi o qeu voce pediu, está tudo de acordo: 
Os arquivos estäo todos salvos na mesma pasta. 
Todos os arquivos estäo com os devidos "#include".

(obs: se voce ver os codigos do professor, verá que ele escreveu "complexos" e eu, "complexo". Mudei todos os nomes dos #include pra ficar certo). 

(obs 2: näo vejo tanta necessidade de rodar meus códigos assim, pelo menos até agora. A näo ser que seja cobrado no futuro em MC202, näo faco questäo que funcione). 

Atte,
