### ISSUE TITLE
[lab03] Erro de memória ao criar lista

### ISSUE THREAD

**Issue by ghost** [iagoac/mc202#60]
Bom dia,

Estou tendo problemas com manejo de memória no meu programa.

Quando eu testei para os exemplos que estão no pdf do lab, os resultados foram os esperados. Porém, em nenhum teste do Susy meu programa passou, segue o que ele apontou:
![image](https://user-images.githubusercontent.com/63800462/81581115-ac114300-9384-11ea-8d45-5859aec0c9b4.png)
Há de se ressaltar que, no teste 1, estes resultados que divergiram sucedem vários resultados corretos

Após isso, eu tentei usar um programa similar ao valgrind para depurar onde estava errando com a memória. Baixei o programa Dr. Memory, pois não utilizo o Linux para conseguir usar o valgrind. Assim, o Dr. Memory apontou o seguinte:
![image](https://user-images.githubusercontent.com/63800462/81581501-335eb680-9385-11ea-9373-6b3431d50fc5.png)
De acordo com a documentação do software: "If the application reads from addressable memory that has not been written to since it was allocated, Dr. Memory reports an "uninitialized read" error"
(https://dynamorio.org/drmemory_docs/page_uninit.html)

Ok, tenho um problema na minha função que cria a lista circular duplamente encadeada.
Depois de muito tempo analisando esta função, ainda não consigo enxergar o meu problema. Segue a função: 
![image](https://user-images.githubusercontent.com/63800462/81581972-d9122580-9385-11ea-8a02-a704a61b8972.png)
Detalhe de que na minha main, eu chamo esta função antes de realizar qualquer operação na lista.

Struct client: 
![image](https://user-images.githubusercontent.com/63800462/81582186-1971a380-9386-11ea-8193-ffa70377fdd7.png)

**Comment by ghost** [comment]
O programa estava apontando para um erro no lugar errado.

**Comment by iagoac** [comment]
@Muelas-234944 antes de te responder, só te pedir uma coisa: por favor, sempre que postar código, copie o texto e cole aqui no formato de algoritmo ao invés de postar screenshots de seu arquivo.  
Desta forma, fica muito mais fácil para que eu, um dos PAD/PED ou um colega te ajudar.

---

> Quando eu testei para os exemplos que estão no pdf do lab, os resultados foram os esperados

Os exemplos do PDF são pequenos exemplos, simples e fáceis de serem resolvidos. Eles estão lá só para mostrar um exemplo de entrada e saída e ilustrar o comportamento esperado do algoritmo.  
Seu código funcionar naqueles pequenos exemplos não quer dizer muita coisa, pois eles não conseguem capturar a complexidade total do problema que vocês estão resolvendo. Por isso é que temos diversos casos de teste (e casos de teste escondidos).

> Há de se ressaltar que, no teste 1, estes resultados que divergiram sucedem vários resultados corretos

Não entendi seu questionamento

**Comment by iagoac** [comment]
Bem, já que você fechou a _issue_, acredito que esteja tudo corrigido.  
Caso você tenha mais dúvidas, favor abrir outra _issue_
