### ISSUE TITLE
codigo 137

### ISSUE THREAD

**Issue by lugavt** [iagoac/mc202#62]
Professor, em todos os testes o meu resultado é o mesmo do esperado, mas quando eu submeto em metade dele aparece o "erro de processamento 
tempo máximo de processamento excedido (código 137)". Alguma sugestão de como prosseguir?

**Comment by iagoac** [comment]
Seu código (provavelmente) está em algum _loop_ infinito e não para de executar. Desta forma, o Susy mata seu algoritmo para não sobrecarregar o servidor
