### ISSUE TITLE
Susy - consideracoes

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#64]
Boa noite,

Como é o caso de muitos, meu codigo está dando erro, devido ao compilamento do Susy. Gostaria de saber o que é o codigo 134 e como será considerada a nota, uma vez que em certos testes constou como correto e em outros, deu erro de compilacao.

Para as proximas vezes, gostaria de saber como resolver esse problema.
Atte,

**Comment by iagoac** [comment]
@ianloron00 este erro 134 do Susy é como o _segmentation fault_ que vocês obtem pelo GCC.  
Ele realmente acontece por erros de acesso a memória, como um duplo _free()_ ou utilização de ponteiros de forma errada.

> em certos testes constou como correto e em outros, deu erro de compilacao.

É um erro em tempo de execução e não de compilação. Seu código está compilando OK

> gostaria de saber como resolver esse problema.

Bem... o que todos podem fazer é debugar o código. Nestes casos, o _gdb_ e o _valgrind_ podem ajudar muito
