### ISSUE TITLE
Lab 3 - Erro e dúvidas!!

### ISSUE THREAD

**Issue by eduarda-nicoletto** [iagoac/mc202#65]
Boa noite!
Quando tento compilar meu programa, sempre aparece segmentationa fault. Procurei os erros de todas as formas mas não consigo achar. No SuSy aparece 
"tamanho máximo da pilha ou da memória dinâmica excedido, 
ou talvez apontador inválido (código 139)"
poderia me ajudar com isso?

**Comment by iagoac** [comment]
@eduarda-nicoletto eu nem consegui compilar seu código.  

Ele está com um erro na linha 16 `nova=malloc(sizeof(populacao));`. Note que `nova` é somente um ponteiro e não faz sentido você alocar algo do tamanho de `populacao`.

Além disso, você tem um erro no momento de andar na lista com o segundo atendente.  
Atualmente, você busca o cliente do atendente 1 e o exclui da lista. Logo após, você busca o cliente do atendente 2 desconsiderando o cliente excluído pelo atendente 1.  
Você deve encontrar os clientes de ambos os atendentes e só depois exclui-los. Uma discussão sobre este problema já aconteceu [aqui](https://github.com/iagoac/mc202/issues/59)
