### ISSUE TITLE
Pedido de prorrogação de prazo.

### ISSUE THREAD

**Issue by sayfelanjos** [iagoac/mc202#66]
Caro Professor, O Laboratório 03 estava com o enunciado muito confuso o que gerou muitas dificuldades. Acho que faltou mais exemplos e clareza no que realmente era para ser feito. Fato esse que se justifica nos poucos alunos que conseguiram submeter. Eu gostaria de pedi-lo, se   possível for, que estenda um pouco mais o prazo deste laboratório para que tenhamos como esclarecer melhor as dúvidas persistentes e com isso realizar a atividade. Além do mais, essa semana tenho tido provas e acredito que meus colegas também, o que acaba limitando o tempo, digo isso pois estrutura de dados é uma matéria que demanda bastante tempo de dedicação.

**Comment by iagoac** [comment]
Prorrogado até quarta feira
