### ISSUE TITLE
Lab4 com testes e submissão indisponíveis

### ISSUE THREAD

**Issue by carlosecb** [iagoac/mc202#68]
Os testes do lab4 não aparecem, e não é possível a submissão do mesmo no susy

**Comment by iagoac** [comment]
@enoque confere isso?

**Comment by carlosecb** [comment]
Aparentemente voltou ao normal

**Comment by iagoac** [comment]
Provavelmente foi só alguma inconsistência no sistema, como um pico de acesso ou falta de energia momentânea. Por favor, me avise caso encontre outro problema semelhante
