### ISSUE TITLE
Tarefa submit não está instalada 

### ISSUE THREAD

**Issue by Hunterms** [iagoac/mc202#69]
Olá!
meu lab já deu certo, mas eu havia esquecido de salvar o nome dele como lab3.c (foi main.c) e n tinha comentado o código tbm.
fui enviar o lab com as alterações e o susy retornou esse mensagem quando tentei submeter o lab e recuperar o lab que eu ja tinha enviado

**Comment by iagoac** [comment]
@Hunterms este é novo para mim :)  
Em qual página você está tentando submeter a tarefa?

Vou verificar como/onde/por quê este erro ocorre.

**Comment by Hunterms** [comment]
Desculpa a demora haha
enviei por essa página aqui: https://susy.ic.unicamp.br:9999/mc202defg/03/
tentei novamente e retornou a mesma mensagem

**Comment by iagoac** [comment]
@Hunterms qual sua turma e RA?

**Comment by Hunterms** [comment]
186289, a turma é a E!

**Comment by iagoac** [comment]
Não sei de onde veio este bug :(

Notei que você fez uma submissão incorreta e uma correta.  Sua submissão correta foi validada pelo Susy na turma E. Desta forma, você não terá nenhum prejuízo de nota caso deixe tudo como está agora.

Entretanto, caso você realmente faça questão de trocar o código, nós podemos tentar resolver este problema.

**Comment by Hunterms** [comment]
Não faço questão! haha
Se o problema persistir no lab 4 eu comento nessa issue mesmo! 
Obrigado!!
