### ISSUE TITLE
Professor, por favor, gostaria de saber quando vão começar a sair os laboratórios?

### ISSUE THREAD

**Issue by Lublanski** [iagoac/mc202#7]

**Comment by iagoac** [comment]
Como dito nos emails, os laboratórios estão sendo desenvolvidos.
Acredito que semana que vem o primeiro já estará disponível.

Eu não vou lançar um a cada semana: pretendo lançar diversos laboratórios de uma só vez (cada qual com sua data de entrega), para que o próprio aluno possa ditar o seu ritmo de trabalho.
