### ISSUE TITLE
Lab4 quebra de linha

### ISSUE THREAD

**Issue by carlosecb** [iagoac/mc202#70]
No enunciado do lab4 a saída deve ser um inteiro e uma quebra de linha, porém a submissão só funciona sem a quebra de linha

**Comment by iagoac** [comment]
@carlos-ecb eu verifiquei e realmente parece que este é o caso.  
Vou mudar a descrição do laboratório e fixar esta _issue_ para que todos possam ver.

**Comment by iagoac** [comment]
Descrição do problema atualizada
