### ISSUE TITLE
Número total de submissões do Lab04

### ISSUE THREAD

**Issue by FelipeWyatt** [iagoac/mc202#72]
Gostaria de saber o número máximo de submissões no Susy do Laboratório 4. Todos os Labs terão o mesmo número máximo de submissões?

**Comment by iagoac** [comment]
@FelipeWyatt elas estão fixadas em 20.  
Até o momento, ninguém chegou próximo destas 20 submissões em um lab. Caso seja necessário, eu posso aumentar no futuro.
