### ISSUE TITLE
Publicação de labs passados os prazos

### ISSUE THREAD

**Issue by carlosecb** [iagoac/mc202#74]
Gostaria de publicar os labs com prazos passados no meu github.
Teria problema em deixar o repositório público? Ou é melhor deixá-lo fechado por conta da possibilidade de entrega em atraso dos labs ao final do semestre?

**Comment by iagoac** [comment]
@carlos-ecb realmente, melhor não fazer isto por hora, pois todos ainda podem entregar os labs em atraso.  
Crie um repositório privado e vá adicionando o que você quiser. Assim que o semestre acabar, fique a vontade para torna-lo público.

**Comment by iagoac** [comment]
@carlosecb já pode criar seu repositório!
