### ISSUE TITLE
funcao "itoa"

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#75]
Boa noite,

Estou tentando utilizar a funcao itoa, sugerida no arquivo do lab4, mas nao em [-Werror] consta como declaracao de funcao implícita... Como faco para rodá-la?

Eu inclui as bibliotecas <stdlib.h> e <stdio.h>

**Comment by arthurlopes** [comment]
Não é possivel usar essa função no susy, como discutido na issue #56 .

**Comment by carlosecb** [comment]
Não seria interessante a retirada da sugestão do uso da função itoa?

**Comment by iagoac** [comment]
@carlos-ecb isso foi feito algumas horas atrás
