### ISSUE TITLE
Erro apenas no teste 17

### ISSUE THREAD

**Issue by ghost** [iagoac/mc202#76]
Apenas no teste 17 , o site está dizendo que o resultado está incorreto. Como resolver isso?

**Comment by GuilhermePascon** [comment]
No meu também, já revirei o código procurando o que é mas não descobri, se alguém tiver alguma dica agradeço muito.

EDIT: Descobri o que era, não estava considerando todos os casos de borda. Talvez essa informação possa ajudar.

**Comment by ghost** [comment]
O que era?

**Comment by nuncaseiescolher** [comment]
verifica seu código pra ver o que acontece caso o menor numero seja zero

**Comment by JobsonAlmeida** [comment]
> O que era?

          Eu também estava enroscado nesse teste 17. Descobri o que era. Aparentemente o teste 17 verifica a saída para uma sequência de zeros. Se o resultado for formado por uma sequência de zeros, a saída deve ser um único zero. Por exemplo, para a o teste extremo 

10000000000000000000000 1.

o meu programa estava gerando uma sequência de zeros como saída. Contudo, a saída deve ser formada por um único zero. Verifica tipos de testes neste estilo. Ou seja, quando a saída é uma sequência de zeros.

          Verificar casos que geram o menor número zero, mas não um sequência de zeros não é o que o teste 17 analisa, aparentemente. Por exemplo, o meu programa estava gerando a saída correta para casos do tipo 12034 4. Porém, mesmo assim não passava no teste 17.

**Comment by JobsonAlmeida** [comment]
Eu também estava enroscado nesse teste 17. Descobri o que era. Aparentemente o teste 17 verifica a saída para uma sequência de zeros. Se o resultado for formado por uma sequência de zeros, a saída deve ser um único zero. Por exemplo, para a o teste extremo 

10000000000000000000000 1.

o meu programa estava gerando uma sequência de zeros como saída. Contudo, a saída deve ser formada por um único zero. Verifica tipos de testes neste estilo. Ou seja, quando a saída é uma sequência de zeros.

Verificar casos que geram o menor número zero, mas não um sequência de zeros não é o que o teste 17 analisa, aparentemente. Por exemplo, o meu programa estava gerando a saída correta para casos do tipo 12034 4. Porém, mesmo assim não passava no teste 17.

**Comment by JobsonAlmeida** [comment]
Eu também estava enroscado nesse teste 17. Descobri o que era. Aparentemente o teste 17 verifica a saída para uma sequência de zeros. Se o resultado for formado por uma sequência de zeros, a saída deve ser um único zero. Por exemplo, para a o teste extremo

10000000000000000000000 1.

o meu programa estava gerando uma sequência de zeros como saída. Contudo, a saída deve ser formada por um único zero. Verifica tipos de testes neste estilo. Ou seja, quando a saída é uma sequência de zeros.

Verificar casos que geram o menor número zero, mas não um sequência de zeros não é o que o teste 17 analisa, aparentemente. Por exemplo, o meu programa estava gerando a saída correta para casos do tipo 12034 4 (ou seja, um único zero). Porém, mesmo assim não passava no teste 17.

**Comment by ghost** [comment]
Eu também estava enroscado nesse teste 17. Descobri o que era. Aparentemente o teste 17 verifica a saída para uma sequência de zeros. Se o resultado for formado por uma sequência de zeros, a saída deve ser um único zero. Por exemplo, para a o teste extremo

10000000000000000000000 1.

o meu programa estava gerando uma sequência de zeros como saída. Contudo, a saída deve ser formada por um único zero. Verifica tipos de testes neste estilo. Ou seja, quando a saída é uma sequência de zeros.

Verificar casos que geram o menor número zero, mas não um sequência de zeros não é o que o teste 17 analisa, aparentemente. Por exemplo, o meu programa estava gerando a saída correta para casos do tipo 12034 4 (ou seja, saída com um único zero). Porém, mesmo assim não passava no teste 17.

**Comment by lucas-vecina** [comment]
Nossa, estava com o mesmo problema. Segui as dicas acima e funcionou. Quando minha pilha tinha todos os seus elementos iguais a zero, não imprimia nada. Bastou um `if` para resolver isso.
Obrigado pelas dicas pessoal!

**Comment by enoque** [comment]
Os casos de bordas sempre são os mais chatos :)

**Comment by cahr118** [comment]
Estou com esse problema ainda :( Fiz a validação pra tratar os casos em que a saída seria uma sequência de zeros, mas ainda recebo falha no teste 17. Alguém poderia me ajudar? @enoque @iagoac 

Exemplos de teste já validados no meu algoritmo: 
in: 1100000 2 out: 0
in: 10001000 2 out: 0
...

Muito obrigado desde já

**Comment by iagoac** [comment]
@cahr118 este não é o caso de teste. Mas como seu algoritmo está funcionando para estes dois exemplos, me é muito estranho que ele não funcione para o teste 17

**Comment by cahr118** [comment]
Sim, também estou achando estranho :/ Teria algo que eu poderia fazer pra checar melhor isso? Estou usando gdb e valgrind já, mas como esses casos de teste descritos acima estão funcionando e o comportamento está como esperado, não estou conseguindo chegar na resposta final.

**Comment by 218913** [comment]
Meu código deu o resultado correto para todos os testes menos o 17. Quando o resultado é 0 meu código tem apenas um 0 como saída, quando existem zeros a esquerda do número o código tbm não imprimi zeros desnecessários. Ja testei todos os números imagináveis e deu certo. Como resolver o problema? O arquivo 17 está realmente correto?

**Comment by iagoac** [comment]
Sim, o teste 17 está realmente correto.  
Diversos alunos já submeteram seus códigos com sucesso, tendo obtido a resposta correta para todos os testes.

**Comment by ghost** [comment]
> Meu código deu o resultado correto para todos os testes menos o 17. Quando o resultado é 0 meu código tem apenas um 0 como saída, quando existem zeros a esquerda do número o código tbm não imprimi zeros desnecessários. Ja testei todos os números imagináveis e deu certo. Como resolver o problema? O arquivo 17 está realmente correto?

Testa esses casos para ver se ajuda a descobrir o problema no teste 17. Eu fiz vários testes, um deles foi o teste dessas condições

10000000000000000000000 1
10000000000000000000000 0

00000000000000000000000 0

**Comment by 218913** [comment]
> > Meu código deu o resultado correto para todos os testes menos o 17. Quando o resultado é 0 meu código tem apenas um 0 como saída, quando existem zeros a esquerda do número o código tbm não imprimi zeros desnecessários. Ja testei todos os números imagináveis e deu certo. Como resolver o problema? O arquivo 17 está realmente correto?
> 
> Testa esses casos para ver se ajuda a descobrir o problema no teste 17. Eu fiz vários testes, um deles foi o teste dessas condições
> 
> 10000000000000000000000 1
> 10000000000000000000000 0
> 
> 00000000000000000000000 0
> 00000000000000000000000 1

testei os 4 casos e deu td certo tbm

**Comment by 218913** [comment]
Na monitoria o ped não conseguiu me ajudar por não saber qual é o teste 17. 
Professor Iago ,visto que somente o senhor sabe o teste 17, tem como me ajudar a resolver este problema?

**Comment by cahr118** [comment]
@iagoac Ainda também estou com problemas pra esse teste, mesmo o código passando pra todos os testes citados aqui nessa thread :(

**Comment by 218913** [comment]
> @iagoac Ainda também estou com problemas pra esse teste, mesmo o código passando pra todos os testes citados aqui nessa thread :(

tenta ver se ta pulando linha depois do zero, o ped revisou meu código e me ajudou a achar este erro no meu

**Comment by iagoac** [comment]
Então, vamos lá: a entrada do teste 17 é 

7508413024741436476856 20

**Comment by michell-lucino** [comment]
Também estou travado em apenas um teste, o 18, não sei se ele possui relação com o 17. Como todos os outros testes dão certo, estou com dificuldade de encontrar o caso específico que causa o problema. Poderia me dar alguma dica do caso que tenho que utilizar para validar meu código, @iagoac?

**Comment by iagoac** [comment]
O 18 não tem nenhuma estrutura tão específica quanto o 17. Desta forma, não tem muito sentido abrir este teste, como foi feito com o 17
