### ISSUE TITLE
resultado incorreto: 1-1-1

### ISSUE THREAD

**Issue by sentineladonorte** [iagoac/mc202#78]
![image](https://user-images.githubusercontent.com/60854016/82130590-14a45980-97a3-11ea-9148-9e549a401515.png)

![image](https://user-images.githubusercontent.com/60854016/82130709-35b97a00-97a4-11ea-901b-95087df3f54b.png)

Quando passo os testes na minha maquina eles dão certo, porem quando passo no susy acontece isso, alguém sabe oque pode ser?

**Comment by iagoac** [comment]
@RafaelAllves não consigo te ajudar só com as informações que você está me dando.  

O meu _chute_, com o que temos por hora, é que seu PC está utilizando uma versão diferente de alguma biblioteca ou função do que a utilizada pelo Susy.  
Mas isso realmente é só um chute e tem uma pequena probabilidade de estar correto :(

Você consegue dar mais informações sobre o que está acontecendo?

**Comment by sentineladonorte** [comment]
desculpe professo e q eu não sei quais informações passar. 
eu passei os teste abertos um por um e as saidas estão corretas, msm assim mudei a logica e os erros persistiram, tentei rodar o programa em outro pc para tentar verificar se era algo relacionado somente ou meu pc porem o progama tbm funcionou no outro pc.
em uma das vezes q passei meu codigo no susy, eu mandei um programa q ia ter saidas erradas de proposito, as saidas seriam algumas somas simples para verificar se essas saidas apareceriam no lugar dos "1-1-1" mas n ocorreu.
as bibliotecas q estou usando são a stdio.h e a stdlib.h

**Comment by iagoac** [comment]
Bem, nenhum aluno nunca reportou este erro antes e realmente fica muito difícil de eu conseguir te responder com as informações até o momento.  

Por favor, tente procurar o bug em seu código até a data final de submissão.  
Caso realmente você não consiga e seu código esteja rodando OK em um PC, podemos conversar sobre alguma outra forma de avaliação na quinta.

**Comment by JonasRoberto** [comment]
Professor, estou com o mesmo problema aqui. a unica diferença com oque ele reportou é que eu usei mais uma biblioteca #include <string.h> , mas o caso é o mesmo, eu testei as entradas e estão certas, mas quando mando no Susy as saidas são as mesmas que a dele tudo -1

**Comment by iagoac** [comment]
@JonasRoberto o mesmo serve para você então.  
Sugiro que ambos conversem entre si para identificar o _bug_ que está ocorrendo.

O Susy compila os códigos utilizando o `gcc 4.8.5`. Mais especificamente, ele utiliza o seguinte comando para compilação:  
`gcc -std=c99 -pedantic -Wall -lm -o labX *.c`  
Tentem compilar exatamente desta forma para ver o que acontece.

**Comment by sentineladonorte** [comment]
Professor, utilizei as msm flags para a compilação e não apresentou nenhum erro nem warning, as saidas continuam corretas no meu pc porem o msm erro ocorre ao ser jogado no susy.
vou continuar a procura do bug

**Comment by enoque** [comment]
Esse problema já foi resolvido? Qual sistema operacional vocês estão usando?

Pode ser que você esteja usando alguma função especifica do seu SO.

**Comment by JonasRoberto** [comment]
Um PED me ajudou a resolver o meu lab4, estou usando o repl.it no final o problema era uma flag que fazia o codigo ser lido de forma errada

**Comment by sentineladonorte** [comment]
@JonasRoberto vc usou o repl.it pra compilar? pode da uma ajuda, ainda n entendi o problema

**Comment by sentineladonorte** [comment]
@enoque to usando o Linux mint

**Comment by JonasRoberto** [comment]
Eu fiz uma parte com vetor, nessa, um dos erros era na verdade uma flag porque eu criei um vetor assim: char str[n][0], o problema foi o [0] que eu precisava criar um int cor=0 e depois substituir no vetor, assim: str[n][cor] e aparentemente essa mesma flag fez com que meu codigo fosse lido fora de parametro e deu as mesmas saidas que as suas no Susy. Esse foi o problema no meu código. O repl.it não tem dava nenhum problema na construção do código, por isso não conseguia encontrar o erro, foi preciso a ajuda de um PED para entender o problema.

**Comment by sentineladonorte** [comment]
Consegui solucionar o meu problema, o Brenner(PED) me ajudou a encontrar o erro. Em resumo, o susy não aceitou que eu utilizasse a função atoi()
