### ISSUE TITLE
Problema de acesso Susy

### ISSUE THREAD

**Issue by leticia-rosa** [iagoac/mc202#79]
Olá, não estou conseguindo mais acessar o Susy. Estava acessando normalmente até pouco tempo atrás mas agora não carrega. Mais alguém com esse problema?

**Comment by leo-leao** [comment]
Estou com o mesmo problema

**Comment by iagoac** [comment]
O Susy teve alguma instabilidade no final de semana, por motivos desconhecidos a mim.  
Entretanto, me parece que já voltou a normalidade.
