### ISSUE TITLE
MakeFile

### ISSUE THREAD

**Issue by Lublanski** [iagoac/mc202#8]
Professor, qual a diferença de compilar usando o make, e compilar apenas o arquivo main?

**Comment by Lublanski** [comment]
Eu meu pc parece que não está reconhecendo o comando make, ele aponta o seguinte erro:
"make: *** No targets specified and no makefile found.  Stop."

**Comment by carlosecb** [comment]
Compilar usando make exige que você tenha um arquivo Makefile, o qual descreve os comandos pra compilar. Pra projetos com um arquivo só compilar direto com o gcc é normalmente mais fácil
