### ISSUE TITLE
Dúvida algoritmo - Lab4

### ISSUE THREAD

**Issue by eduarda-nicoletto** [iagoac/mc202#82]
Olá, estou com dúvida no algoritmo do lab4. Não estou conseguindo pensar em alguma forma de achar o número que não seja calcular todas as possibilidades e imprimir a menor. Acredito que haja forma mais eficiete e rápida, mas não consigo descobrir qual é. Alguém poderia ajudar com isso?

**Comment by iagoac** [comment]
@eduarda-nicoletto basicamente a ideia é esta sim :)  
Uma forma de resolver o problema é testar todas as permutações de _k_ dígitos do número que você recebe de entrada. Uma forma eficiente de você testar isto é utilizando uma pilha.

**Comment by eduarda-nicoletto** [comment]
obrigada, prof.!
