### ISSUE TITLE
dúvida lab4 - comecando com '0'

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#83]
Professor, nesse lab, o número pode comecar com 0?

**Comment by GuilhermePascon** [comment]
Não sou o professor mas acho que posso ajudar, a resposta é não.

**Comment by iagoac** [comment]
Quanto a entrada: **Não**
Quanto a saída: **Sim**

Inclusive, esta é a resposta para um dos testes que diversas pessoas estão tendo problema.
