### ISSUE TITLE
Entendimento Entrada x Saída

### ISSUE THREAD

**Issue by victorpmacc** [iagoac/mc202#84]
Estive hoje realizando o laboratório e, quando pensei que havia finalizado, percebi que a relação entrada x saída não é a que eu tinha entendido à priori. Alguém consegue me explicar com outras palavras?
Havia entendido que se temos um valor de N dígitos, retiramos k dígitos e devemos formar o menor valor possível. Ex (arq01.in): 6827445236721725525994, removemos os k=18 maiores dígitos: **6827445**2**367**21**7**2**5525994**. A resposta seria 1222, mas o arq01.res indica que é 1224. Qual o problema na interpretação? o que exatamente devo entregar na saída? Lendo os outros teste continuei com essa confusão

**Comment by iagoac** [comment]
@victorpmacc a resposta é 1224. Você não pode alterar a ordem dos números.  
Note que só existem dois números `2` após o `1`. Neste caso, a resposta (marcado em negrito) é  
682744523672**1**7**2**55**2**599**4**

**Comment by iagoac** [comment]
Seria muito trivial simplesmente remover os _k_ maiores dígitos. O que você deve fazer é remover _k_ dígitos tal que o número restante seja o menor possível.

**Comment by enoque** [comment]
Só para ficar mais claro: a ordem dos dígitos não deve ser alterada. Com o numero 54321 você não consegue formar o numero 1234 removendo um numero, por exemplo.

**Comment by victorpmacc** [comment]
Entendi! Obrigado!
