### ISSUE TITLE
[lab4] Pilha

### ISSUE THREAD

**Issue by alimarques** [iagoac/mc202#85]
Vi que o laboratório pode ser feito com pilhas, mas necessariamente tem que ser com pilhas? Vai ser descontado ponto se for com outra estrutura?

**Comment by marinabmorais** [comment]
Pelo que está escrito no enunciado parece que voce pode usar a estrutura que quiser, pq eles colocaram o uso de pilhas apenas como "dica"

**Comment by iagoac** [comment]
@alimarques a ideia realmente seria implementr com pilhas.  
Até o momento, já vi alguns alunos implementando uma pilha utilizando listas duplamente encadeadas (o que não deixa de ser uma pilha, mas é muito mais difícil de programar).  
Também já vi alguns alunos utilizando outras abordagens, o que geralmente leva a erros e a não verificação dos casos de borda, assim, fazendo com que alguns testes específicos não funcionem.

Eu não vou tirar pontos de quem não implementar uma pilha, pois isto não foi definido como restrição na descrição do laboratório, como @m-abi disse aqui
