### ISSUE TITLE
Dificuldade de assimilação do conteúdo no formato atual.

### ISSUE THREAD

**Issue by 218913** [iagoac/mc202#86]
Existe alguma explicação para não ter aula dessa disciplina via ead? Apenas os slides não são suficientes e não da pra acompanhar pelos vídeos gravados em 2018 pois só mostram o áudio e não o que o professor está escrevendo no quadro...

**Comment by 218913** [comment]
> Estou tendo dificuldades para assimilar o conteúdo pois apenas os slides  as aulas de 2018 (que embora tenho o áudio gravado não mostram a lousa nem o que o professor esta escrevendo) há alguma explicação para não ter aula dessa disciplina via ead? Como em outras matérias?

**Comment by ghost** [comment]
Até o momento não estou achando que os slides e as vídeos aulas não são suficientes. Os vídeos da disciplina que foram gravados não mostram a lousa, porém é possível compreender tranquilamente o que o professor diz. Toda a aula é baseada na sequência de slides. Lembro apenas de um exemplo que o professor explicou na lousa que não entendi, mas não foi nada relevante.
Esse formato com vídeos está sendo muito bom para mim. Eu posso assistir a qualquer hora sem ter que estar presente na frente do computador em determinado horário para ter presença.

**Comment by iagoac** [comment]
@JobsonAlmeida @218913 podemos discutir uma alteração no formato para já entrar em funcionamento na próxima semana.

Eu tenho duas propostas:  
1. Aulas normais, dando prosseguimento a disciplina (a partir da data que está marcada aqui no git)
2. Aulas de dúvidas, nas quais ficarei online para responder dúvidas sobre **QUALQUER** assunto referente a disciplina, desde listas encadeadas até algoritmos em grafos, árvores e hashs.

Eu tenho uma tendência a preferir o segundo formato, pois ele realmente serviria como apoio a disciplina. Além disso, como cada aluno está estudando uma parte da disciplina, acredito que assim seja mais fácil englobar a todos

**Comment by lugavt** [comment]
acredito que a proposta 2 seja englobe mais a necessidade dos alunos

**Comment by iagoac** [comment]
Alguém tem alguma outra proposta?

**Comment by nuncaseiescolher** [comment]
Dentre as duas propostas acredito que a segunda seja mais atrativa para todos os alunos, entretanto já temos vários horários disponívei de monitorias justamente para tirar dúvidas. O conteúdo é difícil e devemos usar as monitorias com frequência, acredito que quem esteja tendo dificuldades ainda não procurou este tipo de ajuda.

Na minha opinião tudo poderia continuar como está.

**Comment by wellingtondiaspereira** [comment]
Acredito que a segunda proposta seja a mais interessante. As aulas gravadas são muito boas, além de dar flexibilidade de horário. Acho que uma opção de horário de dúvidas seria suficiente para o bom andamento da disciplina. 
Fora isso ainda temos os horários de monitoria, o que, no meu caso, acredito ser mais do que suficiente para resolver os labs a tempo.

**Comment by Alandroid** [comment]
Eu estou achando o formato atual muito bom, pois dá uma autonomia aos alunos que poucas disciplinas nos fornecem. Também nos aproxima mais do formato de trabalho de desenvolvimento de algoritmos em projetos reais. 
Talvez aumentar o número de monitorias para atendimento geral seria bom, mas acredito que aulas com teoria só iriam gerar um trabalho enorme ao professor sem grande contrapartida em termos de aprendizado

**Comment by Antonio-Silvestre** [comment]
Concordo com o que foi dito pelos colegas acima, já existem espaços para tirar dúvidas, as aulas gravadas são muito boas e o modelo atual gera flexibilidade e acredito que satisfaz a gigante maioria dos alunos, acho válido abrir mais horários de monitorias, caso seja necessário. Fora isso, acho que tudo corre bem nessa disciplina.

**Comment by arthurlopes** [comment]
Estou fazendo uma materia que combina um pouco as duas opcoes citadas. O professor faz uma revisao rapida (30-45min) da materia no cronograma da ultima seamana e depois abre para duvidas sobre qualquer parte da materia.

**Comment by arthurlopes** [comment]
> Estou fazendo uma materia que combina um pouco as duas opcoes citadas. O professor faz uma revisao rapida (30-45min) da materia no cronograma da ultima seamana e depois abre para duvidas sobre qualquer parte da materia.

E esta "aula" é opcional

**Comment by iagoac** [comment]
Vou deixar aqui aberto para discussões.  
No Domingo (24/05) eu volto para saber qual é a melhor opção.

>  acho válido abrir mais horários de monitorias, caso seja necessário

Eu poderia facilmente dobrar a carga horária semanal de monitorias, com novos horários a serem combinados com os PEDs e PADs.

**Comment by leticia-rosa** [comment]
O modelo dos vídeos tem funcionado razoavelmente bem pra mim, só sinto falta da aula de laboratório em que teríamos mais tempo pra tirar dúvidas dos labs do que nas monitorias, que as vezes acaba nao sendo sufiente. Então eu acho que se tivessemos um horario fixo, como foi proposto, para cada turma para tirar dúvidas além das monitorias poderia ser de grande ajuda pra quem tem mais dificuldade pra fazer os labs, ou algo do tipo seguindo essa proposta de mais tempo disponível pra tirar dúvidas e referente a problemas com os labs.

**Comment by FelipeWyatt** [comment]
Estive em uma monitoria em que o PAD e eu demoramos o tempo completo agendado para a monitoria para resolver um problema no meu código, caso mais algum aluno entrasse para tirar dúvida não haveria tempo. Dessa forma, acredito que aumentar o número de horários de atendimento é uma boa forma de melhorar a disciplina. Então alunos com dificuldade/problemas poderiam recorrer mais ao atendimento.

**Comment by laryssalgr** [comment]
Gosto do formato atual pelo aluno ter autonomia quanto ao seu estudo e horários, mas acredito que as aulas poderiam ter mais alguns recursos voltados ao formato EAD, como um quadro para visualização do conteúdo passado por áudio, ou uma gravação exclusiva para esse formato para que possamos assimilar o que está sendo dito junto a recursos visuais.

**Comment by iagoac** [comment]
Bem, pelo que foi comentado aqui, pode-se observar os seguintes tópicos

1. Alguns alunos acham interessante uma aula semanal de dúvidas e outros alunos não acham interessante. 
2. Um maior horário e abrangência das monitorias seria benéfico a todos.

Desta forma, vou abrir um horário semanal para tirar dúvidas acerca da disciplina (e não sobre os laboratórios). Além disto, vou negociar com os PADs e com os PEDs um aumento na carga horária semanal de monitorias.  

Enviarei mais notícias em breve.
