### ISSUE TITLE
makefile lab4

### ISSUE THREAD

**Issue by ianloron00** [iagoac/mc202#87]
No enunciado do lab4, nao ficou muito claro como deve ser essa implementacao das estruturas de dados... Devemos utilizar o makefile? Como que o Susy compila?

**Comment by iagoac** [comment]
@ianloron00 está descrito na página inicial aqui do Github

O Susy compila os códigos utilizando o gcc 4.8.5. Mais especificamente, ele utiliza o seguinte comando para compilação:
`gcc -std=c99 -pedantic -Wall -lm -o labX *.c`

---

Vocês podem implementar da maneira que quiserem e submeter até 5 arquivos diferentes (entre `.c` e `.h`). O que o Susy faz é compilar todos os `.c` em conjunto, como no exemplo acima

**Comment by ianloron00** [comment]
entendi... Entao nao compila `.o` como nos exemplos da aula 4, certo? Podemos dividir apenas em `.c` e `.h`, e sem precisar de Makefile?

**Comment by iagoac** [comment]
Exatamente. O Susy já possui um makefile interno bem mais complexo do que esta pequena linha de código que eu mandei.  
A submissão deve conter somente os arquivos `.c` e `.h`.

**Comment by victorpmacc** [comment]
Professor, a divisão do código em diferentes arquivos é opcional certo? Digo, se enviado apenas um `.c`, sem divisão de arquivo para as funções, cliente etc, a entrega continua validada normalmente?? Nos últimos labs entreguei apenas arquivo único `.c`.

**Comment by iagoac** [comment]
@victorpmacc sim, é opicional. Aumentei o número de arquivos para dar mais liberdade a vocês, mas nada impede a submissão de um único arquivo `.c`
