### ISSUE TITLE
Erro apenas no Teste 18 - Lab4

### ISSUE THREAD

**Issue by TauaneLemeB1** [iagoac/mc202#88]
Professor, poderia me dar alguma dica para que eu saiba pq só está dando erro no Teste 18?

**Comment by enoque** [comment]
Você está tratando os 0's a esquerda? Provavelmente esse teste possui pelo menos um zero a esquerda.

**Comment by TauaneLemeB1** [comment]
@enoque acredito que sim. Por exemplo, a entrada é:   20564   3 
A saída seria 04, porém como é zero a esquerda a saída será apenas 4. Certo?

**Comment by enoque** [comment]
É isso msm.

Olhei o teste aqui e não me parece ter nada de especial no teste, além do zero a esquerda. Como você está fazendo?

Caso o problema ainda persista e estiver tudo para o @iagoac , informo qual é a entrada e tentamos resolver olhando diretamente para entrada.

**Comment by michell-lucino** [comment]
Também estava com dificuldade no teste 18, mas identifiquei o problema ao realizar o seguinte:

Entrada: 1101101100 5
É pra saída ser 100.

Caso o seu retorne algo diferente, vale rever a questão dos zeros a esquerda.

**Comment by iagoac** [comment]
É a última vez que vou abrir um teste fechado.

5809819419854526383709 16
