### ISSUE TITLE
Dúvida sobre o Lab1

### ISSUE THREAD

**Issue by leo-leao** [iagoac/mc202#9]
Boa noite professor, tudo bem?
Com relação ao Lab1, a matriz precisa ser alocada dinamicamente ou posso estabelecer um máximo para o tamanho? Outro questionamento, existe algum método específico que devo utilizar para separar os valores dados no input para uma linha da matriz (ex: "10 20 30") ou posso utilizar qualquer alternativa como as possíveis na biblioteca string.h?

**Comment by enoque** [comment]
Boa noite, Leo!! Sobre a parte de alocação dinâmica, nesse primeiro lab ainda não precisa se preocupar com isso (spoiler, uma matriz de tamanho 100x100 já é bem mais que o suficiente).  Sobre o input, basta usar o scanf("%d", &variavel) normalmente, o scanf já ignora todo espaço e quebra de linha que tiver na entrada.
