### ISSUE TITLE
Lab's 5 e 6

### ISSUE THREAD

**Issue by frangupe** [iagoac/mc202#90]
Bom dia professor, visto que as datas de entrega dos lab's 5 e 6 já estão definidas, seria possivel liberar os dois ao mesmo tempo?

**Comment by iagoac** [comment]
Sim, a ideia era liberar ontem a noite.  Mas, tivemos um pequeno problema com o Susy e não conseguimos fechar tudo a tempo.

Vamos disponibilizar ambos os laboratórios hoje durante o dia

**Comment by frangupe** [comment]
Ok, obrigado.
