### ISSUE TITLE
Entrega atrasada de um Lab

### ISSUE THREAD

**Issue by GabrielBarrosoVentura** [iagoac/mc202#91]
Eu tive problemas com o Lab3 e isso atrasou meu Lab4, acabei apenas agora (um dia depois da entrega). No começo do curso o senhor disse que poderíamos entregar os Labs com 75% da nota até o final do semestre caso não fosse concluído no prazo.

como faço para realizar essa entrega ? e quando poderei realiza-la ? uma vez que o susy não está permitindo a entrega atrasada do Lab.

**Comment by iagoac** [comment]
@GabrielBarrosoVentura vou trabalhar para reabrir as submissões dos labs 01 a 04 nesta próxima semana. Para isto, será criada uma nova tarefa no Susy.

Enviarei um email a todos quando a submissão estiver aberta

**Comment by alisonaran** [comment]
Caro Iago, boa noite!
Irei entregar os laboratórios fora do prazo. Qual a data limite? O susy já está liberado para entrega atrasada? Obrigado!
