### ISSUE TITLE
Duvida lab 05

### ISSUE THREAD

**Issue by leo-leao** [iagoac/mc202#93]
Teria como liberar alguns testes de tamanho menor (que não os 100.000 do susy) e que não os apenas de 5 valores do enunciado para que possamos realizar mais testes de mesa? Fica bem complicado ter um salto tão grande na quantidade e não ter uma noção do que pode estar acontecendo e porque da divergência de valores.

**Comment by enoque** [comment]
Posso gerar do tamanho que você quiser. Me fale de qual tamanho quer.

**Comment by leo-leao** [comment]
Se puder gerar um com 15 e outro 20, ficaria muito grato kkk

**Comment by leo-leao** [comment]
Não precisa mais enoque! Deu bom kkkkk, muito obrigado
