### ISSUE TITLE
Resultados do susy para a tarefa 7

### ISSUE THREAD

**Issue by ghost** [iagoac/mc202#94]
Quando eu submeto o programa, o site do susy está mostrando

Teste 01: resultado incorreto
49030							      \	49030
Teste 02: resultado incorreto
17430							      \	17430
Teste 03: resultado incorreto
48372							      \	48372
Teste 04: resultado incorreto
66404							      \	66404
Teste 05: resultado incorreto
16081							      \	16081
Teste 06: resultado incorreto
7086							      \	7086
Teste 07: resultado incorreto
58689							      \	58689
Teste 08: resultado incorreto
22441							      \	22441
Teste 09: resultado incorreto
76269							      \	76269

O que há de incorreto nas minhas saídas?

**Comment by enoque** [comment]
Provavelmente você não colocou o '\n' ou colocou algum espaço antes ou depois.
