### ISSUE TITLE
Lab 07 enunciado

### ISSUE THREAD

**Issue by frangupe** [iagoac/mc202#95]
No enunciado do lab07 está dizendo que a saída deverá ser o k-ésimo maior número, no entanto, no próprio exemplo do pdf, a resposta correspondente é o k-ésimo menor número.
Por exemplo, para a seguinte entrada:
> 6 2 
> 3 5 3 2 9 2

O segundo (k = 2) maior número é 5, e não 2 como apontado na resposta (2 seria o segundo menor numero).
> 6 6
> 6 5 4 3 2 1

O sexto maior número seria "1", enquanto o primeiro maior número seria "6".

**Comment by enoque** [comment]
Realmente está errado. Fiz esses exemplos uns dias depois de fazer o enunciado e acabei zuando msm.

Vlw por avisar, vou arrumar o pdf.

**Comment by enoque** [comment]
Algumas pessoas já submeteram, então pra não bagunçar as coisas vou alterar para o 'k-ésimo menor número' msm.

**Comment by GFranciscoP** [comment]
@enoque Ok, mas eu já envei para o susy da forma que deu certo, será necessário submeter novamente?
