### ISSUE TITLE
Enunciado lab05

### ISSUE THREAD

**Issue by pedro-ferraz** [iagoac/mc202#96]
Boa tarde,
Após observar o enunciado do lab05 e compará-lo com os testes abertos do susy, me surgiu uma dúvida:

O enunciado diz que a variável "N" trata da quantidade de elementos de um vetor que será ordenado pelo Mergesort:
![entrada lab05](https://user-images.githubusercontent.com/63692033/82841538-d8f94600-9eac-11ea-9cbb-b633eb03ccb2.png)

O que fica comprovado pelos exemplos de entrada onde há **um único vetor** com 5 elementos:
![tabela lab05](https://user-images.githubusercontent.com/63692033/82841580-00e8a980-9ead-11ea-9e58-6668cbec92ed.png)

Entretanto, os testes abertos do susy mostram, na verdade, que "N" trata, aparentemente, da **quantidade de vetores** de entrada (separados por espaço), entre os quais existem tamanhos diversos e, como consequência, uma quantidade muito maior de elementos do que se esperava:
![susy lab05](https://user-images.githubusercontent.com/63692033/82841753-9ab05680-9ead-11ea-840e-568383089c83.png)

Aqui pode-se ver a quantidade real de elementos (caracteres sem espaço) e que o "N" (100000) representa a quantidade de vetores de inteiros ("Palavras"):
![word lab05](https://user-images.githubusercontent.com/63692033/82841815-d519f380-9ead-11ea-9867-fc5da3e87981.png)

Portanto a minha dúvida é se houve algum equívoco nos testes do susy ou no enunciado do lab05, ou se é alguma interpretação errada minha acerca do enunciado.

Obrigado!

**Comment by leonardosrodrigues0** [comment]
Pelo que eu entendi, na verdade, é apenas 1 vetor que deve ser ordenado. Ele contém nesse caso 100000 inteiros que são os números sem espaço.

**Comment by nuncaseiescolher** [comment]
Sua interpretação está errada, a entrada é um único vetor com 100.000 elementos, contados como palavras, na imagem que você mandou do contador.
Nesse mesmo exemplo que você mandou a primeira posição do vetor contém o número 9200, a segunda 89867, a terceira 167 e etc.

**Comment by pedro-ferraz** [comment]
Ah ficou claro agora. Vlw galera!
