### ISSUE TITLE
Estrutura de dados para os labs 5 e 7

### ISSUE THREAD

**Issue by leonardosrodrigues0** [iagoac/mc202#97]
Posso usar um simples vetor com alocação estática para armazenar os dados nesses labs ou a restrição _"Você deverá implementar qualquer estrutura de dados que utilizar"_ implica que devo implementar alguma estrutura?

**Comment by iagoac** [comment]
Implica que você deve implementar algo, caso faça a utilização dela, como um vetor ou uma lista.  
Entretanto, não é literalmente necessário que você utilize alguma destas estruturas nestes labs.

**Comment by leonardosrodrigues0** [comment]
Certo professor, obrigado.
