### ISSUE TITLE
Planejamento de aulas

### ISSUE THREAD

**Issue by igorloss500** [iagoac/mc202#98]
Professor, não sei se foi proposital, mas desde a última vez que você atualizou o "read me", as datas para cada assunto sumiram. Eu estava me baseando nisso para andar com a matéria e ter noção se estava acompanhando. 

Poderia por favor, informar se mudaremos o formato ou se poderia adicionar as datas novamente?

Atenciosamente,
Igor

**Comment by iagoac** [comment]
@igorloss500 as datas estão todas lá. Elas nunca foram removidas

![image](https://user-images.githubusercontent.com/8388583/83170155-79887980-a0ea-11ea-9650-2094fa1f4061.png)
