### ISSUE TITLE
código 134 susy

### ISSUE THREAD

**Issue by arthurcbaia** [iagoac/mc202#99]
Boa tarde, 
estou tendo um problema com o susy, no qual ele aponta como memória corrompida, procurei saber o que era na internet mas acabei não encontrando o porque do erro, dado que ele tem haver com a liberação do vetor dinâmico. Estou utilizando três arquivos e uma variável global há alguma relação ?

**Comment by iagoac** [comment]
@arthurcbaia infelizmente, este erro não é próprio do C, mas sim algo incluído no Susy.  
Este erro já foi discutido em diversos pontos aqui neste fórum (principalmente durante os laboratórios 02 e 03). Ele é o equivalente a uma [falha de segmentação](https://pt.wikipedia.org/wiki/Falha_de_segmenta%C3%A7%C3%A3o) ([_segmentation fault_](https://en.wikipedia.org/wiki/Segmentation_fault)) do C e C++
